//! A voice-activated teleprompter generated by `krate create`.
//!
//! The app receives bounded PCM audio only after the person grants microphone
//! access. When the bundle carries a local Whisper model, the Krate runtime
//! transcribes each spoken phrase without exposing the user's filesystem or
//! network. A visible voice-activity fallback keeps manual control available.

#[allow(warnings)]
mod bindings;

use bindings::krate::audio::{capture, types as audio_types};
use bindings::krate::io::{args, stdio};
use bindings::krate::speech::transcription;
use bindings::krate::ui::{events, tree, types, window};

const ROOT_ID: u64 = 1;
const TITLE_ID: u64 = 2;
const CURRENT_LINE_ID: u64 = 3;
const NEXT_LINE_ID: u64 = 4;
const STATUS_ID: u64 = 5;
const BACK_ID: u64 = 6;
const NEXT_ID: u64 = 7;

const SCRIPT: [&str; 6] = [
    "Welcome. Take a breath and begin when you are ready.",
    "Krate made this app from one plain request.",
    "It listens only after you approve microphone access.",
    "The app receives only the capability you allowed.",
    "The same file can open on Mac, Windows, and Linux.",
    "That is how AI made software becomes easier to share.",
];

const SAMPLE_RATE: u32 = 16_000;
const CHANNELS: u16 = 1;
const BUFFER_FRAMES: u32 = 960;
const AUDIO_READ_BYTES: u32 = 8_192;
const SPEECH_THRESHOLD: u32 = 900;
const SILENT_ROUNDS_TO_ADVANCE: u8 = 7;
const WAIT_MILLIS: u32 = 50;
const MAX_ROUNDS: u32 = 600_000;
const MODEL_ASSET: &str = "models/ggml-tiny.en.bin";

struct Component;

fn pure_string(text: &str) -> String {
    let bytes = text.as_bytes();
    let len = bytes.len();
    if len == 0 {
        return String::new();
    }
    unsafe {
        let layout = core::alloc::Layout::from_size_align_unchecked(len, 1);
        let ptr = std::alloc::alloc(layout);
        if ptr.is_null() {
            #[cfg(target_arch = "wasm32")]
            core::arch::wasm32::unreachable();
            #[cfg(not(target_arch = "wasm32"))]
            std::process::abort();
        }
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr, len);
        String::from_raw_parts(ptr, len, len)
    }
}

#[allow(clippy::too_many_arguments)]
fn node(
    id: u64,
    parent: Option<u64>,
    kind: types::WidgetKind,
    label: Option<String>,
    role: Option<String>,
    width: f32,
    height: f32,
    grow: f32,
    padding: f32,
) -> types::WidgetNode {
    types::WidgetNode {
        id,
        parent,
        kind,
        label,
        role,
        style: types::Style {
            width: Some(width),
            height: Some(height),
            grow,
            padding,
        },
        checked: None,
        value: None,
        selected: None,
        text_cursor: None,
    }
}

fn root() -> types::WidgetNode {
    node(
        ROOT_ID,
        None,
        types::WidgetKind::Stack,
        None,
        None,
        720.0,
        500.0,
        0.0,
        28.0,
    )
}

fn text_node(id: u64, text: &str, role: &str, height: f32) -> types::WidgetNode {
    let mut n = node(
        id,
        Some(ROOT_ID),
        types::WidgetKind::Text,
        Some(pure_string(text)),
        Some(pure_string(role)),
        656.0,
        height,
        0.0,
        0.0,
    );
    n.role = Some(pure_string(role));
    n
}

fn button(id: u64, label: &str) -> types::WidgetNode {
    node(
        id,
        Some(ROOT_ID),
        types::WidgetKind::Button,
        Some(pure_string(label)),
        Some(pure_string("button")),
        160.0,
        36.0,
        0.0,
        0.0,
    )
}

fn rebuild(
    win: u64,
    line: usize,
    listening: bool,
    speaking: bool,
    recognition: Option<&str>,
) -> bool {
    let status = if let Some(recognition) = recognition {
        recognition
    } else if !listening {
        "Microphone unavailable"
    } else if speaking {
        "Listening: voice detected"
    } else {
        "Listening: speak to advance"
    };
    let next = SCRIPT.get(line + 1).copied().unwrap_or("End of script");
    tree::set_root(win, &root()).is_ok()
        && tree::upsert_node(
            win,
            &text_node(TITLE_ID, "Voice Prompter", "heading", 34.0),
        )
        .is_ok()
        && tree::upsert_node(
            win,
            &text_node(
                CURRENT_LINE_ID,
                SCRIPT.get(line).copied().unwrap_or("End of script"),
                "heading",
                150.0,
            ),
        )
        .is_ok()
        && tree::upsert_node(win, &text_node(NEXT_LINE_ID, next, "text", 90.0)).is_ok()
        && tree::upsert_node(win, &text_node(STATUS_ID, status, "status", 28.0)).is_ok()
        && tree::upsert_node(win, &button(BACK_ID, "Previous")).is_ok()
        && tree::upsert_node(win, &button(NEXT_ID, "Next")).is_ok()
}

fn peak_pcm_s16(bytes: &[u8]) -> u32 {
    let mut peak = 0u32;
    let mut index = 0usize;
    while index + 1 < bytes.len() {
        let Some(low) = bytes.get(index).copied() else {
            break;
        };
        let Some(high) = bytes.get(index + 1).copied() else {
            break;
        };
        let sample = i16::from_le_bytes([low, high]);
        peak = peak.max(sample.unsigned_abs() as u32);
        index += 2;
    }
    peak
}

impl bindings::Guest for Component {
    fn run() -> i32 {
        let quick = args::raw()
            .as_bytes()
            .split(|byte| *byte == b'\n')
            .next()
            .is_some_and(|first| first == b"quick");
        if quick {
            let out = stdio::stdout();
            let _ = out.write(b"voice-prompter:local-speech-ready\n");
            return 0;
        }

        let size = types::WindowSize {
            width: 720,
            height: 500,
        };
        let Ok(win) = window::create("Voice Prompter", size) else {
            return 30;
        };
        if window::show(win).is_err() {
            return 31;
        }

        let config = audio_types::StreamConfig {
            sample_rate: SAMPLE_RATE,
            channels: CHANNELS,
            format: audio_types::SampleFormat::PcmS16,
            buffer_frames: BUFFER_FRAMES,
        };
        let Ok(stream) = capture::open(config) else {
            let _ = rebuild(win, 0, false, false, None);
            return 40;
        };
        if capture::start(stream).is_err() {
            let _ = rebuild(win, 0, false, false, None);
            return 41;
        }

        let mut line = 0usize;
        let mut speaking = false;
        let mut silent_rounds = 0u8;
        let _ = rebuild(win, line, true, speaking, None);

        for _ in 0..MAX_ROUNDS {
            match events::wait(Some(WAIT_MILLIS)) {
                Some(types::Event::Pointer(pointer))
                    if pointer.pressed && pointer.widget == Some(BACK_ID) =>
                {
                    line = line.saturating_sub(1);
                    let _ = rebuild(win, line, true, speaking, None);
                }
                Some(types::Event::Pointer(pointer))
                    if pointer.pressed && pointer.widget == Some(NEXT_ID) =>
                {
                    if line + 1 < SCRIPT.len() {
                        line += 1;
                    }
                    let _ = rebuild(win, line, true, speaking, None);
                }
                Some(types::Event::Key(key)) if key.pressed && key.key.as_bytes() == b"ArrowLeft" => {
                    line = line.saturating_sub(1);
                    let _ = rebuild(win, line, true, speaking, None);
                }
                Some(types::Event::Key(key))
                    if key.pressed && key.key.as_bytes() == b"ArrowRight" =>
                {
                    if line + 1 < SCRIPT.len() {
                        line += 1;
                    }
                    let _ = rebuild(win, line, true, speaking, None);
                }
                Some(types::Event::CloseRequested(_)) => break,
                _ => {}
            }

            let Ok(bytes) = capture::read(stream, AUDIO_READ_BYTES) else {
                let _ = rebuild(win, line, false, false, None);
                break;
            };
            let heard_voice = peak_pcm_s16(&bytes) >= SPEECH_THRESHOLD;
            if heard_voice {
                silent_rounds = 0;
                let current = SCRIPT.get(line).copied().unwrap_or("");
                let _ = transcription::match_line_stream(
                    MODEL_ASSET,
                    &bytes,
                    SAMPLE_RATE,
                    Some("en"),
                    current,
                    false,
                );
                if !speaking {
                    speaking = true;
                    let _ = rebuild(win, line, true, true, None);
                }
            } else if speaking {
                silent_rounds = silent_rounds.saturating_add(1);
                let finish = silent_rounds >= SILENT_ROUNDS_TO_ADVANCE;
                let current = SCRIPT.get(line).copied().unwrap_or("");
                let result = transcription::match_line_stream(
                    MODEL_ASSET,
                    &bytes,
                    SAMPLE_RATE,
                    Some("en"),
                    current,
                    finish,
                );
                if finish {
                    speaking = false;
                    silent_rounds = 0;
                    match result {
                        Ok(Some(score)) if score >= 35 => {
                            if line + 1 < SCRIPT.len() {
                                line += 1;
                            }
                            let _ = rebuild(
                                win,
                                line,
                                true,
                                false,
                                Some("Matched your words locally"),
                            );
                        }
                        Ok(_) => {
                            let _ = rebuild(
                                win,
                                line,
                                true,
                                false,
                                Some("Listening for the words on screen"),
                            );
                        }
                        Err(_) => {
                            let _ = rebuild(
                                win,
                                line,
                                true,
                                false,
                                Some("Local speech model not included; use the arrow controls"),
                            );
                        }
                    }
                }
            }
        }

        let _ = capture::stop(stream);
        let _ = window::close(win);
        0
    }
}

bindings::export!(Component with_types_in bindings);
