use std::fs;
use std::hash::{DefaultHasher, Hash, Hasher};
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=../../.git/HEAD");

    let rustc = command_output("rustc", &["-V"]).unwrap_or_else(|| "unknown".to_owned());
    let git_sha = command_output("git", &["rev-parse", "--short=12", "HEAD"])
        .unwrap_or_else(|| "unknown".to_owned());

    println!("cargo:rustc-env=KRATE_RUSTC_VERSION={rustc}");
    println!("cargo:rustc-env=KRATE_GIT_SHA={git_sha}");

    embed_sdk();
}

/// Embed the guest SDK — the WIT interface definitions and the Rust bindings
/// crate — into the binary, so `krate create` can materialize a self-contained
/// SDK at runtime and build a generated app without a repo checkout.
///
/// A generated file in OUT_DIR lists every SDK file as (relative path, bytes),
/// each included from a blob so the payload lives in the binary's rodata rather
/// than in generated source. The Rust bindings crate's `Cargo.toml` inherits
/// fields from the workspace (`version.workspace = true`, ...), which do not
/// resolve once the crate stands alone, so that one file is rewritten to
/// concrete values before embedding.
fn embed_sdk() {
    // The cli crate is crates/cli; the repo root is two levels up.
    let repo_root = PathBuf::from(env("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
        .to_path_buf();
    let out_dir = PathBuf::from(env("OUT_DIR"));

    // (relative path under the materialized SDK root, source bytes).
    let mut files: Vec<(String, Vec<u8>)> = Vec::new();

    // The WIT trees for both phases.
    for wit in ["wit/krate/phase2", "wit/krate/phase3"] {
        collect_dir(&repo_root, &repo_root.join(wit), &mut files);
    }

    // The Rust bindings crate. Its Cargo.toml is rewritten to stand alone.
    let bindings = repo_root.join("crates/bindings-rust");
    for rel in ["README.md", "src/lib.rs", "src/bindings.rs"] {
        let path = bindings.join(rel);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        files.push((format!("crates/bindings-rust/{rel}"), bytes));
    }
    let cargo_toml = bindings.join("Cargo.toml");
    println!("cargo:rerun-if-changed={}", cargo_toml.display());
    let standalone = standalone_bindings_cargo_toml(&cargo_toml);
    files.push((
        "crates/bindings-rust/Cargo.toml".to_string(),
        standalone.into_bytes(),
    ));

    // Cache identity must follow SDK contents, including uncommitted local WIT
    // changes. A git SHA alone reused a stale materialized SDK while developing
    // a new interface.
    let mut sdk_hasher = DefaultHasher::new();
    for (path, bytes) in &files {
        path.hash(&mut sdk_hasher);
        bytes.hash(&mut sdk_hasher);
    }
    println!(
        "cargo:rustc-env=KRATE_SDK_FINGERPRINT={:016x}",
        sdk_hasher.finish()
    );

    // Emit the embedded-file table, one include_bytes! per file.
    let mut out = String::new();
    out.push_str("// Generated by build.rs. The embedded guest SDK.\n");
    out.push_str("pub static EMBEDDED_SDK: &[(&str, &[u8])] = &[\n");
    for (rel, bytes) in &files {
        let safe = rel.replace(['/', '.', '-'], "_");
        let blob = out_dir.join(format!("sdk_{safe}.blob"));
        fs::write(&blob, bytes).expect("write blob");
        out.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            blob.to_string_lossy()
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("embedded_sdk.rs"), out).expect("write embedded_sdk.rs");
}

/// Walk `dir`, recording every file with a path relative to `root`.
///
/// Every file is watched individually, not just the directory holding it.
/// Watching only directories misses a whole new subdirectory: adding
/// `wit/krate/phase2/deps/random/` created a path this walk had never seen, so
/// cargo saw nothing changed, skipped the rebuild, and left a materialized SDK
/// whose world imported a package its own deps tree did not contain. Every
/// build after that failed with "package 'krate:random@0.1.0' not found".
fn collect_dir(root: &Path, dir: &Path, files: &mut Vec<(String, Vec<u8>)>) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir).unwrap_or_else(|e| panic!("read dir {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            collect_dir(root, &path, files);
        } else {
            println!("cargo:rerun-if-changed={}", path.display());
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            let bytes = fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            files.push((rel, bytes));
        }
    }
}

/// Rewrite the bindings crate's Cargo.toml so it needs no parent workspace:
/// replace each `field.workspace = true` with the concrete value.
fn standalone_bindings_cargo_toml(path: &Path) -> String {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut out = String::new();
    for line in text.lines() {
        let replacement = match line.trim() {
            "version.workspace = true" => Some("version = \"0.1.0-dev\""),
            "edition.workspace = true" => Some("edition = \"2021\""),
            "license.workspace = true" => Some("license = \"MIT OR Apache-2.0\""),
            "repository.workspace = true" => {
                Some("repository = \"https://github.com/incyashraj/krate\"")
            }
            "rust-version.workspace = true" => Some("rust-version = \"1.91\""),
            _ => None,
        };
        match replacement {
            Some(value) => {
                out.push_str(value);
                out.push('\n');
            }
            None => {
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    out
}

fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| panic!("{key} not set"))
}

fn command_output(program: &str, args: &[&str]) -> Option<String> {
    let output = Command::new(program).args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }

    Some(String::from_utf8_lossy(&output.stdout).trim().to_owned())
}
