// Generated by scripts/sdk-phase3-layer.py from bindings_gui.rs. DO NOT EDIT.

//! The Phase 3 interfaces -- windows, widgets, events, drawing, sound,
//! camera, speech -- as thin layers over the gui world's bindings
//! (IC-298). Same signatures, same errors, same states; the SDK is the
//! one place an app reaches them, whichever world it targets.

#![allow(clippy::too_many_arguments)]

/// `krate:ui`: clipboard, dialog, events, image, launcher, menu, notify, tree, window.
pub mod ui {
    /// `krate:ui/clipboard`.
    pub mod clipboard {
        pub use crate::bindings::krate::ui::clipboard::UiError;

        /// Read UTF-8 text from the host clipboard.
        pub fn read_text() -> Result<alloc::string::String, UiError> {
            crate::bindings::krate::ui::clipboard::read_text()
        }

        /// Write UTF-8 text to the host clipboard.
        pub fn write_text(text: &str) -> Result<(), UiError> {
            crate::bindings::krate::ui::clipboard::write_text(text)
        }
    }
    /// `krate:ui/dialog`.
    pub mod dialog {
        pub use crate::bindings::krate::ui::dialog::{ChosenFile, ChosenFolder, UiError};

        /// Show a simple message dialog.
        pub fn message(window: u64, title: &str, body: &str) -> Result<(), UiError> {
            crate::bindings::krate::ui::dialog::message(window, title, body)
        }

        /// Ask a yes/no question and return true for yes.
        pub fn confirm(window: u64, title: &str, body: &str) -> Result<bool, UiError> {
            crate::bindings::krate::ui::dialog::confirm(window, title, body)
        }

        /// Show the system's open-file dialog.
        ///
        /// `filter` is a comma-separated extension list such as `"png,jpg"`, or an
        /// empty string for any file. It is a hint to the dialog, not a rule the
        /// runtime enforces -- what the person picks is what the app gets.
        pub fn open_file(
            window: u64,
            title: &str,
            filter: &str,
        ) -> Result<Option<ChosenFile>, UiError> {
            crate::bindings::krate::ui::dialog::open_file(window, title, filter)
        }

        /// Ask the person to choose a folder, and return what they chose.
        ///
        /// This is how an app reaches a real folder of theirs: not by naming a
        /// path (no path can be named), and not by asking for everything, but by
        /// the person picking one -- and the pick IS the grant. The app can then
        /// use every fs call under `picked/<token>/...` for this run: list what
        /// is there, read files, write results, make subfolders. The grant ends
        /// with the run; nothing about the folder's location is learnable; and a
        /// tidy-my-folder app needs exactly this and no fs capability at all.
        ///
        /// `none` means they cancelled, which is a normal outcome and not an
        /// error. Requires the `ui.dialog:open-folder` capability.
        pub fn open_folder(window: u64, title: &str) -> Result<Option<ChosenFolder>, UiError> {
            crate::bindings::krate::ui::dialog::open_folder(window, title)
        }
    }
    /// `krate:ui/events`.
    pub mod events {
        pub use crate::bindings::krate::ui::events::Event;

        /// Return the next queued event without blocking, if one is waiting.
        pub fn poll() -> Option<Event> {
            crate::bindings::krate::ui::events::poll()
        }

        /// Wait until the next event arrives or the timeout expires.
        pub fn wait(timeout_millis: Option<u32>) -> Option<Event> {
            crate::bindings::krate::ui::events::wait(timeout_millis)
        }

        /// Whether a key is held down right now.
        ///
        /// A game asks "is W down", not "was W pressed". An app can track this from
        /// press and release events, and every app that tries gets the same bug: the
        /// window loses focus while a key is held, the release is delivered to
        /// somebody else, and the player keeps running forever. The host sees focus
        /// changes and clears held keys on one, so this is the only place the
        /// question can be answered correctly.
        ///
        /// Key names are the same ones `key-event` reports.
        pub fn key_held(key: &str) -> bool {
            crate::bindings::krate::ui::events::key_held(key)
        }

        /// Whether a gamepad is connected and usable.
        ///
        /// An app should ask before showing "press A to start", and fall back to the
        /// keyboard when this is false rather than leaving somebody staring at a
        /// prompt for a controller they do not own.
        pub fn gamepad_connected() -> bool {
            crate::bindings::krate::ui::events::gamepad_connected()
        }

        /// Whether a gamepad button is held down right now.
        ///
        /// Names are the ones every controller shares regardless of what is printed
        /// on it: `south`, `east`, `west`, `north` for the face buttons, `l1`, `r1`,
        /// `l2`, `r2` for the shoulders, `start`, `select`, and `dpad-up`,
        /// `dpad-down`, `dpad-left`, `dpad-right`.
        ///
        /// Positional rather than lettered because the same physical button is A on
        /// an Xbox pad and B on a Nintendo one. An app that asks for `south` gets
        /// the button under the player's thumb on both.
        pub fn gamepad_held(button: &str) -> bool {
            crate::bindings::krate::ui::events::gamepad_held(button)
        }

        /// A stick or trigger position, from -1 to 1.
        ///
        /// Axis names: `left-x`, `left-y`, `right-x`, `right-y`, `l2`, `r2`. Up and
        /// right are positive. Triggers report 0 to 1 rather than -1 to 1, because
        /// a trigger has no negative direction and reporting one would mean every
        /// app remapping it.
        ///
        /// Returns 0 when no gamepad is connected, so an app that never checks still
        /// behaves as though the sticks are centred rather than drifting.
        pub fn gamepad_axis(axis: &str) -> f32 {
            crate::bindings::krate::ui::events::gamepad_axis(axis)
        }
    }
    /// `krate:ui/image`.
    pub mod image {
        pub use crate::bindings::krate::ui::image::{ImagePixels, UiError};

        /// Give an image widget its picture. Replaces any picture it already had.
        pub fn set_pixels(window: u64, widget: u64, pixels: &ImagePixels) -> Result<(), UiError> {
            crate::bindings::krate::ui::image::set_pixels(window, widget, pixels)
        }

        /// Take a picture away, leaving an empty frame.
        pub fn clear(window: u64, widget: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::image::clear(window, widget)
        }
    }
    /// `krate:ui/launcher`.
    pub mod launcher {
        pub use crate::bindings::krate::ui::launcher::LaunchError;

        /// Ask the operating system to open a URL in whatever the person uses.
        ///
        /// Returns once the request is handed over, not when the page has loaded:
        /// the app gets no signal about what the browser then did, which is what
        /// keeps this from becoming a channel back into the app.
        pub fn open_url(url: &str) -> Result<(), LaunchError> {
            crate::bindings::krate::ui::launcher::open_url(url)
        }
    }
    /// `krate:ui/menu`.
    pub mod menu {
        pub use crate::bindings::krate::ui::menu::{MenuItem, UiError};

        /// Set the simple top-level menu for a window.
        pub fn set_items(window: u64, items: &[MenuItem]) -> Result<(), UiError> {
            crate::bindings::krate::ui::menu::set_items(window, items)
        }
    }
    /// `krate:ui/notify`.
    pub mod notify {
        pub use crate::bindings::krate::ui::notify::NotifyError;

        /// Show one notification.
        ///
        /// The host attributes it to the app, so an app cannot post a notification
        /// that appears to come from somewhere else. There is no reply channel: an
        /// app learns nothing about whether the notification was seen or clicked,
        /// which keeps this from becoming a way to watch the person.
        pub fn show(title: &str, body: &str) -> Result<(), NotifyError> {
            crate::bindings::krate::ui::notify::show(title, body)
        }
    }
    /// `krate:ui/tree`.
    pub mod tree {
        pub use crate::bindings::krate::ui::tree::{UiError, WidgetNode};

        /// Set or replace the root widget for a window.
        pub fn set_root(window: u64, root: &WidgetNode) -> Result<(), UiError> {
            crate::bindings::krate::ui::tree::set_root(window, root)
        }

        /// Insert or update one widget node.
        pub fn upsert_node(window: u64, node: &WidgetNode) -> Result<(), UiError> {
            crate::bindings::krate::ui::tree::upsert_node(window, node)
        }

        /// Remove one widget node and its children.
        pub fn remove_node(window: u64, widget: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::tree::remove_node(window, widget)
        }

        /// Move keyboard focus to a widget.
        pub fn focus_node(window: u64, widget: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::tree::focus_node(window, widget)
        }

        /// Enable or disable a widget.
        pub fn set_enabled(window: u64, widget: u64, enabled: bool) -> Result<(), UiError> {
            crate::bindings::krate::ui::tree::set_enabled(window, widget, enabled)
        }
    }
    /// The records and errors this package's interfaces share.
    pub mod types {
        pub use crate::bindings::krate::ui::types::*;
    }
    /// `krate:ui/window`.
    pub mod window {
        pub use crate::bindings::krate::ui::window::{UiError, WindowSize, WindowState};

        /// Create a host window and return its id.
        pub fn create(title: &str, size: WindowSize) -> Result<u64, UiError> {
            crate::bindings::krate::ui::window::create(title, size)
        }

        /// Show a created window.
        pub fn show(window: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::show(window)
        }

        /// Close a window.
        pub fn close(window: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::close(window)
        }

        /// Change the title of a window.
        pub fn set_title(window: u64, title: &str) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::set_title(window, title)
        }

        /// Change the size of a window.
        pub fn set_size(window: u64, size: WindowSize) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::set_size(window, size)
        }

        /// Change the state of a window.
        pub fn set_state(window: u64, state: WindowState) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::set_state(window, state)
        }

        /// Ask the host to schedule a redraw event.
        pub fn request_redraw(window: u64) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::request_redraw(window)
        }

        /// Extend the app's content into the title-bar area (a full-bleed window).
        ///
        /// The host keeps its own window controls overlaid on top, so the window
        /// can always be closed. On hosts whose windowing cannot do this, the call
        /// returns unsupported and the window keeps its standard chrome -- call it
        /// with `let _ =` and design for both.
        pub fn set_full_bleed(window: u64, enabled: bool) -> Result<(), UiError> {
            crate::bindings::krate::ui::window::set_full_bleed(window, enabled)
        }
    }
}

/// `krate:gfx`: canvas2d, scene3d.
pub mod gfx {
    /// `krate:gfx/canvas2d`.
    pub mod canvas2d {
        pub use crate::bindings::krate::gfx::canvas2d::{
            Color, CornerRadii, GfxError, GradientStop, Point, Rect, Size, TextMetrics, TextStyle,
        };

        /// Create or bind a 2D canvas for a window widget.
        pub fn bind(window: u64, widget: u64) -> Result<u64, GfxError> {
            crate::bindings::krate::gfx::canvas2d::bind(window, widget)
        }

        /// The canvas's current size in logical pixels.
        ///
        /// A canvas is laid out to fill its widget, and a widget with siblings or a
        /// resizable window is not the size the app guessed at startup. Ask, then
        /// draw to the answer: an app that hardcodes 240x200 and shares its window
        /// with a title bar draws a picture that is clipped or half empty. Returns
        /// the size that `clear` fills and `present` publishes.
        pub fn canvas_size(canvas: u64) -> Result<Size, GfxError> {
            crate::bindings::krate::gfx::canvas2d::canvas_size(canvas)
        }

        /// Fix the coordinate system an app draws in, and let the host fit it to
        /// whatever window the person has.
        ///
        /// Some apps -- games especially -- have a geometry that only makes sense
        /// at one size: a paddle 48 wide, bricks laid out to span exactly 320.
        /// Asking such an app to recompute every constant from `canvas-size` is a
        /// rewrite, and the usual result is what a real person reported on a real
        /// window: the text drew fine and the character and ground were off the
        /// screen.
        ///
        /// Declare the size the app was designed for and keep drawing in those
        /// coordinates forever. The host scales them UNIFORMLY to fill the window
        /// and centres what is left over, so nothing is ever stretched out of
        /// proportion -- the same letterboxing a console does on a widescreen TV.
        /// Pointer coordinates arrive in design space too, so hit-testing keeps
        /// working without a single change.
        ///
        /// An app that wants to use the extra room rather than letterbox it
        /// should ignore this and lay out from `canvas-size` instead. Both are
        /// honest; this one is for apps whose proportions are the design.
        pub fn set_design_size(canvas: u64, size: Size) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::set_design_size(canvas, size)
        }

        /// Restrict drawing to a rectangle, in logical pixels. Every later draw on
        /// this canvas is trimmed to it until `clear-clip`.
        ///
        /// This is what makes a scrolling list possible. Without it a row scrolled
        /// past the top paints over the header, and an app has to skip rows by hand
        /// -- which works until rows have different heights, and then it cannot be
        /// done at all.
        ///
        /// set-clip(canvas, list-x, list-y, list-w, list-h);
        /// // draw every row, including partly-visible ones
        /// clear-clip(canvas);
        pub fn set_clip(canvas: u64, x: f32, y: f32, w: f32, h: f32) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::set_clip(canvas, x, y, w, h)
        }

        /// Draw to the whole canvas again.
        pub fn clear_clip(canvas: u64) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::clear_clip(canvas)
        }

        /// Fill the whole canvas with one color. Respects the clip, so this is also
        /// how a region is cleared before its rows are redrawn.
        pub fn clear(canvas: u64, fill: Color) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::clear(canvas, fill)
        }

        /// Fill a rectangle.
        pub fn fill_rect(canvas: u64, area: Rect, fill: Color) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::fill_rect(canvas, area, fill)
        }

        /// Stroke a rectangle's edges.
        pub fn stroke_rect(
            canvas: u64,
            area: Rect,
            stroke: Color,
            width: f32,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::stroke_rect(canvas, area, stroke, width)
        }

        /// Fill a rectangle with rounded corners, anti-aliased.
        ///
        /// This is the modern-card primitive: panels, buttons, chips, list rows.
        /// Reach for it whenever a design shows a container with soft corners --
        /// drawing `fill-rect` and four `fill-circle`s by hand never looks right.
        /// A radius of 10-16 reads as a card, height/2 as a pill.
        pub fn fill_round_rect(
            canvas: u64,
            area: Rect,
            radii: CornerRadii,
            fill: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::fill_round_rect(canvas, area, radii, fill)
        }

        /// Stroke a rounded rectangle's edge, anti-aliased, `width` pixels thick.
        /// The outline counterpart to `fill-round-rect`, for bordered cards and
        /// pill buttons drawn hollow.
        pub fn stroke_round_rect(
            canvas: u64,
            area: Rect,
            radii: CornerRadii,
            width: f32,
            stroke: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::stroke_round_rect(
                canvas, area, radii, width, stroke,
            )
        }

        /// A soft shadow under a rounded rectangle: the card's silhouette, blurred
        /// by `blur` pixels and filled with `shadow` (usually black at low alpha,
        /// e.g. a=0.35). Draw it FIRST, offset a few pixels down from the card,
        /// then draw the card over it -- shadow behind, never on top. This is what
        /// lifts a card off the background; without it panels look flat and dated.
        pub fn drop_shadow_round_rect(
            canvas: u64,
            area: Rect,
            radii: CornerRadii,
            blur: f32,
            shadow: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::drop_shadow_round_rect(
                canvas, area, radii, blur, shadow,
            )
        }

        /// Fill a rectangle with a gradient through any number of color stops,
        /// running at `angle-degrees` (0 is left-to-right, 90 is top-to-bottom).
        /// Stops must be sorted by offset, 0.0 to 1.0. Two stops make an ordinary
        /// fade; three or more make the rich backgrounds modern designs use --
        /// e.g. deep blue at 0.0, bright blue at 0.55, near-white at 1.0.
        pub fn linear_gradient_stops(
            canvas: u64,
            area: Rect,
            angle_degrees: f32,
            stops: &[GradientStop],
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::linear_gradient_stops(
                canvas,
                area,
                angle_degrees,
                stops,
            )
        }

        /// Draw text with full styling: weight, italic, letter spacing, and a
        /// generic family. `draw-text` stays as the plain-regular shorthand; this
        /// is what headings, big numbers, and captions want. The same weight
        /// range every design tool uses: a screen usually needs only 400 for
        /// body, 600-700 for emphasis.
        pub fn draw_text_styled(
            canvas: u64,
            text: &str,
            origin: Point,
            font_size: f32,
            ink: Color,
            style: TextStyle,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::draw_text_styled(
                canvas, text, origin, font_size, ink, style,
            )
        }

        /// Measure a styled run with the same layout `draw-text-styled` uses, so
        /// right-aligned numbers and centred labels land exactly.
        pub fn measure_text_styled(
            canvas: u64,
            text: &str,
            font_size: f32,
            style: TextStyle,
        ) -> Result<TextMetrics, GfxError> {
            crate::bindings::krate::gfx::canvas2d::measure_text_styled(
                canvas, text, font_size, style,
            )
        }

        /// Stroke part of a circle: the progress-ring primitive. `start-degrees`
        /// is where the arc begins (0 is 3 o'clock, 90 is 6 o'clock -- angles run
        /// clockwise on screen), `sweep-degrees` how far it runs clockwise. A
        /// progress ring is two calls: the full track at low alpha, then the arc
        /// from -90 (12 o'clock) sweeping `progress * 360`.
        pub fn stroke_arc(
            canvas: u64,
            center: Point,
            radius: f32,
            start_degrees: f32,
            sweep_degrees: f32,
            width: f32,
            stroke: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::stroke_arc(
                canvas,
                center,
                radius,
                start_degrees,
                sweep_degrees,
                width,
                stroke,
            )
        }

        /// Blit RGBA pixels clipped to a rounded rectangle: the photo-card
        /// primitive. Same pixel format as `draw-pixels`; the corners outside the
        /// radii stay untouched, so an image sits inside a card without a mask in
        /// the app.
        pub fn draw_pixels_round(
            canvas: u64,
            area: Rect,
            radii: CornerRadii,
            width: u32,
            height: u32,
            rgba: &[u8],
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::draw_pixels_round(
                canvas, area, radii, width, height, rgba,
            )
        }

        /// Fill an anti-aliased circle centred at `center` with radius `radius`.
        /// The edge is smooth and the fill blends over the canvas by its color's
        /// alpha, so a translucent fill reads as soft light rather than a hard disc.
        pub fn fill_circle(
            canvas: u64,
            center: Point,
            radius: f32,
            fill: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::fill_circle(canvas, center, radius, fill)
        }

        /// Stroke a circle's edge: a ring `width` pixels thick, centred on `radius`.
        ///
        /// The outline counterpart to `fill-circle`, and the thing to reach for when
        /// you want a rim, a ring, a dial, or an unfilled dot. Without it the
        /// nearest available call is `stroke-rect`, which puts a square box around a
        /// round shape -- a real screensaver shipped exactly that.
        pub fn stroke_circle(
            canvas: u64,
            center: Point,
            radius: f32,
            width: f32,
            stroke: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::stroke_circle(
                canvas, center, radius, width, stroke,
            )
        }

        /// A radial gradient disc: `inner` color at the centre easing to `outer` at
        /// `radius`. With `outer` transparent this is a soft glow -- the primitive a
        /// modern look is built from (bloom, light, soft particles).
        pub fn radial_gradient(
            canvas: u64,
            center: Point,
            radius: f32,
            inner: Color,
            outer: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::radial_gradient(
                canvas, center, radius, inner, outer,
            )
        }

        /// A vertical linear gradient filling `area`: `top` color at the top edge
        /// easing to `bottom` at the bottom. For skies, panels, and backdrops.
        pub fn linear_gradient(
            canvas: u64,
            area: Rect,
            top: Color,
            bottom: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::linear_gradient(canvas, area, top, bottom)
        }

        /// Draw one text run with the host's built-in face; `origin` is the baseline.
        pub fn draw_text(
            canvas: u64,
            text: &str,
            origin: Point,
            font_size: f32,
            ink: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::draw_text(canvas, text, origin, font_size, ink)
        }

        /// How big will that text be once drawn?
        ///
        /// The face is proportional: `i` and `W` differ by roughly four times in
        /// real width, so character-count times a constant is not an approximation,
        /// it is wrong -- it is why captions overflow their cards, labels are not
        /// really centred, and carets sit beside the text instead of after it. Ask
        /// instead. The host measures with the same font layout `draw-text` draws
        /// with, so the answer describes the pixels that will appear.
        ///
        /// Use it before drawing, not after: centre a label with
        /// `x + (box_w - m.width) * 0.5`, place a caret at `text_x + m.width`,
        /// stack paragraph lines by `m.height`, and turn a run into a box by
        /// drawing at `top + m.ascent`.
        ///
        /// The measurement is unwrapped and single-line -- it reports what
        /// `draw-text` will do with the same string and size, and `draw-text` does
        /// not wrap. An app laying out a paragraph measures word by word and breaks
        /// the lines itself.
        pub fn measure_text(
            canvas: u64,
            text: &str,
            font_size: f32,
        ) -> Result<TextMetrics, GfxError> {
            crate::bindings::krate::gfx::canvas2d::measure_text(canvas, text, font_size)
        }

        /// Draw decoded RGBA pixels into a rectangle, scaled to fit and centred.
        ///
        /// The same straight-RGBA bytes an image widget takes, so a sprite sheet is
        /// decoded once in the sandbox and drawn many times. Transparent pixels blend
        /// over what is already on the canvas, which is what makes a sprite a sprite
        /// rather than a rectangle with a picture in it.
        pub fn draw_pixels(
            canvas: u64,
            area: Rect,
            width: u32,
            height: u32,
            rgba: &[u8],
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::draw_pixels(canvas, area, width, height, rgba)
        }

        /// Draw a decoded RGBA sprite centred at `center`, scaled to `dst` pixels,
        /// rotated by `angle` radians (clockwise), alpha-blended over the canvas.
        /// `width`/`height` are the source image size; `rgba` is `width*height*4`
        /// straight-alpha bytes. This is what a ship that points where it flies, a
        /// spinning asteroid, or any rotated sprite needs -- the piece that lets a
        /// canvas game reach a real textured-sprite look instead of flat shapes.
        pub fn draw_sprite(
            canvas: u64,
            center: Point,
            dst: Size,
            angle: f32,
            width: u32,
            height: u32,
            rgba: &[u8],
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::draw_sprite(
                canvas, center, dst, angle, width, height, rgba,
            )
        }

        /// Publish the raster to the widget. Until this, nothing is shown.
        pub fn present(canvas: u64) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::canvas2d::present(canvas)
        }
    }
    /// `krate:gfx/scene3d`.
    pub mod scene3d {
        pub use crate::bindings::krate::gfx::scene3d::{Color, GfxError, Lighting};

        /// Create a 3D scene that draws into a window widget.
        pub fn bind(window: u64, widget: u64) -> Result<u64, GfxError> {
            crate::bindings::krate::gfx::scene3d::bind(window, widget)
        }

        /// Clear colour and depth. Call this at the start of every frame.
        pub fn clear(scene: u64, sky: Color) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::clear(scene, sky)
        }

        /// Place the camera: eye, the point it looks at, and vertical field of view
        /// in degrees. Up is +Y.
        pub fn camera(
            scene: u64,
            eye: &[f32],
            look_at: &[f32],
            fov_degrees: f32,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::camera(scene, eye, look_at, fov_degrees)
        }

        /// Direction light travels, as a vector. Surfaces facing into it are lit.
        pub fn light(scene: u64, direction: &[f32]) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::light(scene, direction)
        }

        /// Draw triangles. `vertices` is x,y,z per corner -- nine floats per
        /// triangle -- in world space. Every triangle in one call shares a colour,
        /// which keeps the common case (a mesh in one material) to a single crossing
        /// of the sandbox boundary.
        ///
        /// Facing away from the camera is drawn too: an app that wants back-face
        /// culling is describing a closed mesh, and the host cannot know that.
        pub fn triangles(scene: u64, vertices: &[f32], tint: Color) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::triangles(scene, vertices, tint)
        }

        /// Draw triangles positioned by a transform, without moving the vertices.
        ///
        /// `translate` is x,y,z. `rotate-degrees` is around x, y and z in that
        /// order. `scale` is uniform. The mesh itself is sent unchanged, so an app
        /// can keep one cube and place a hundred of them.
        ///
        /// This exists because the alternative is a matrix multiply per vertex on
        /// the guest side, every frame, with the result crossing the sandbox
        /// boundary -- the most expensive place to put it. A tree of a thousand
        /// leaves is one mesh and a thousand cheap calls rather than a thousand
        /// rebuilt vertex lists.
        pub fn place(
            scene: u64,
            vertices: &[f32],
            translate: &[f32],
            rotate_degrees: &[f32],
            scale: f32,
            tint: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::place(
                scene,
                vertices,
                translate,
                rotate_degrees,
                scale,
                tint,
            )
        }

        /// Upload an image once and get a handle to draw with.
        ///
        /// The same straight-RGBA bytes an image widget takes, so an app decodes a
        /// texture atlas once with `zune-png` inside its own sandbox and keeps the
        /// handle. Sending pixels on every draw would move a megabyte across the
        /// sandbox boundary sixty times a second to show the same wall.
        ///
        /// A texture belongs to its scene and goes away when the scene does.
        pub fn upload_texture(
            scene: u64,
            width: u32,
            height: u32,
            rgba: &[u8],
        ) -> Result<u64, GfxError> {
            crate::bindings::krate::gfx::scene3d::upload_texture(scene, width, height, rgba)
        }

        /// Draw triangles wearing a texture.
        ///
        /// `vertices` is x,y,z per corner as before. `uvs` is u,v per corner -- six
        /// floats per triangle -- where 0,0 is the top-left of the image and 1,1 the
        /// bottom-right. Coordinates outside that range wrap, so a floor can tile a
        /// small image across a large surface.
        ///
        /// `tint` multiplies the sampled colour, so one grey texture can become a
        /// red wall and a blue one without uploading it twice.
        pub fn textured(
            scene: u64,
            vertices: &[f32],
            uvs: &[f32],
            texture: u64,
            tint: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::textured(scene, vertices, uvs, texture, tint)
        }

        /// Draw textured triangles with a normal per corner, so curved surfaces
        /// shade smoothly instead of faceting.
        ///
        /// `normals` is x,y,z per corner -- nine floats per triangle -- and need not
        /// be unit length; the host normalises. The lighting term is interpolated
        /// across the triangle from the three corner normals, which is what turns a
        /// sphere of a few hundred facets into a smooth ball.
        ///
        /// Without this, shading comes from the FACE normal and every triangle is
        /// flat. The only way to look smooth is to subdivide until the facets are
        /// finer than the shading steps between them, which costs triangles for
        /// something a normal per corner gives away.
        ///
        /// Corner normals also make the lighting one-sided, which face normals
        /// cannot be: a face-normal renderer has to take the absolute value of the
        /// light term, because a closed mesh's winding decides which way its normals
        /// point and half of them come out inward. That absolute value lights the
        /// dark side of everything exactly as brightly as the lit side, which is why
        /// a face-shaded scene looks flat however many lights it has.
        pub fn smooth(
            scene: u64,
            vertices: &[f32],
            normals: &[f32],
            uvs: &[f32],
            texture: u64,
            tint: Color,
        ) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::smooth(
                scene, vertices, normals, uvs, texture, tint,
            )
        }

        /// Set how the scene is lit. Refused by a backend that cannot do it, so an
        /// app can ask once at startup and fall back rather than discovering per
        /// frame that nothing changed.
        pub fn set_lighting(scene: u64, lighting: &Lighting) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::set_lighting(scene, lighting)
        }

        /// Skip triangles facing away from the camera.
        ///
        /// Off by default, and that is deliberate: it is only correct for a closed
        /// mesh, where the far side is hidden by the near side anyway. Turn it on
        /// for a cube or a character and roughly half the triangles stop being
        /// filled. Leave it off for a flat floor or a billboard, which have one
        /// visible side and would vanish when viewed from underneath.
        ///
        /// Corners must run counter-clockwise when seen from outside for this to
        /// keep the right half. An app that turns it on and sees its model inside
        /// out has its winding the other way.
        pub fn cull_back_faces(scene: u64, enabled: bool) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::cull_back_faces(scene, enabled)
        }

        /// Publish the frame to the widget. Until this, nothing is shown.
        pub fn present(scene: u64) -> Result<(), GfxError> {
            crate::bindings::krate::gfx::scene3d::present(scene)
        }
    }
    /// The records and errors this package's interfaces share.
    pub mod types {
        pub use crate::bindings::krate::gfx::types::*;
    }
}

/// `krate:audio`: capture, playback.
pub mod audio {
    /// `krate:audio/capture`.
    pub mod capture {
        pub use crate::bindings::krate::audio::capture::{AudioError, StreamConfig};

        /// Open an input stream and return its id.
        pub fn open(config: StreamConfig) -> Result<u64, AudioError> {
            crate::bindings::krate::audio::capture::open(config)
        }

        /// Start capture for an opened stream.
        pub fn start(stream_id: u64) -> Result<(), AudioError> {
            crate::bindings::krate::audio::capture::start(stream_id)
        }

        /// Stop capture for an opened stream.
        pub fn stop(stream_id: u64) -> Result<(), AudioError> {
            crate::bindings::krate::audio::capture::stop(stream_id)
        }

        /// Read interleaved little-endian audio bytes.
        pub fn read(stream_id: u64, max_bytes: u32) -> Result<alloc::vec::Vec<u8>, AudioError> {
            crate::bindings::krate::audio::capture::read(stream_id, max_bytes)
        }
    }
    /// `krate:audio/playback`.
    pub mod playback {
        pub use crate::bindings::krate::audio::playback::{AudioError, StreamConfig};

        /// Open an output stream and return its id.
        pub fn open(config: StreamConfig) -> Result<u64, AudioError> {
            crate::bindings::krate::audio::playback::open(config)
        }

        /// Start playback for an opened stream.
        pub fn start(stream_id: u64) -> Result<(), AudioError> {
            crate::bindings::krate::audio::playback::start(stream_id)
        }

        /// Stop playback for an opened stream.
        pub fn stop(stream_id: u64) -> Result<(), AudioError> {
            crate::bindings::krate::audio::playback::stop(stream_id)
        }

        /// Write interleaved little-endian audio bytes.
        pub fn write(stream_id: u64, bytes: &[u8]) -> Result<u32, AudioError> {
            crate::bindings::krate::audio::playback::write(stream_id, bytes)
        }

        /// Load a short sound once and get a handle to play it with.
        ///
        /// For sound effects: a footstep, a shot, a click. Held in memory decoded,
        /// so playing one costs no device call. Opening a stream takes about two
        /// milliseconds -- an eighth of a frame at sixty per second -- which a game
        /// firing a sound on the frame it happens cannot afford.
        ///
        /// The bytes are interleaved little-endian samples in the stream's own
        /// format, exactly like `write`.
        pub fn load_sound(stream_id: u64, bytes: &[u8]) -> Result<u64, AudioError> {
            crate::bindings::krate::audio::playback::load_sound(stream_id, bytes)
        }

        /// Start a loaded sound playing, mixed with whatever else is sounding.
        ///
        /// Returns immediately; the sound plays to its end on its own. Playing the
        /// same handle again while it is still sounding starts a second copy, which
        /// is what makes rapid fire sound like rapid fire rather than one long note.
        ///
        /// `gain` scales it: 1.0 is as loaded, 0.5 is half as loud. Mixing is
        /// additive and clamped, so a dozen sounds at once distort rather than wrap
        /// around into noise.
        pub fn play_sound(stream_id: u64, sound: u64, gain: f32) -> Result<(), AudioError> {
            crate::bindings::krate::audio::playback::play_sound(stream_id, sound, gain)
        }

        /// Stop every copy of a sound that is currently playing.
        pub fn stop_sound(stream_id: u64, sound: u64) -> Result<(), AudioError> {
            crate::bindings::krate::audio::playback::stop_sound(stream_id, sound)
        }
    }
    /// The records and errors this package's interfaces share.
    pub mod types {
        pub use crate::bindings::krate::audio::types::*;
    }
}

/// `krate:camera`: capture.
pub mod camera {
    /// `krate:camera/capture`.
    pub mod capture {
        pub use crate::bindings::krate::camera::capture::{
            CameraError, DeviceInfo, Frame, FrameInfo, StreamConfig,
        };

        /// The cameras this machine has.
        ///
        /// Empty is a normal answer, not an error: plenty of desktops have no
        /// camera. An app should say so plainly rather than looking broken.
        pub fn devices() -> Result<alloc::vec::Vec<DeviceInfo>, CameraError> {
            crate::bindings::krate::camera::capture::devices()
        }

        /// Open a camera and return its stream id.
        ///
        /// `device` empty means "the default camera". The stream is open but not
        /// running: nothing is captured, and on macOS the operating system's camera
        /// indicator light stays off, until `start`.
        pub fn open(device: &str, config: StreamConfig) -> Result<u64, CameraError> {
            crate::bindings::krate::camera::capture::open(device, config)
        }

        /// What this stream actually opened as. Draw from this, not from the
        /// config you asked for.
        pub fn info(stream_id: u64) -> Result<FrameInfo, CameraError> {
            crate::bindings::krate::camera::capture::info(stream_id)
        }

        /// Begin capturing. The camera indicator light comes on here.
        pub fn start(stream_id: u64) -> Result<(), CameraError> {
            crate::bindings::krate::camera::capture::start(stream_id)
        }

        /// Stop capturing without closing the stream, so `start` can resume it.
        ///
        /// The indicator light goes off. An app that hides its preview should call
        /// this rather than quietly keeping the camera running, and a person can
        /// see the difference.
        pub fn stop(stream_id: u64) -> Result<(), CameraError> {
            crate::bindings::krate::camera::capture::stop(stream_id)
        }

        /// The newest frame, or nothing if none has arrived since the last read.
        ///
        /// Never blocks. Old frames are dropped rather than queued: an app that
        /// draws at 30fps from a 60fps camera should show the newest picture, not
        /// fall further behind. Poll this from the event loop the same way a
        /// network read is polled.
        pub fn read(stream_id: u64) -> Result<Option<Frame>, CameraError> {
            crate::bindings::krate::camera::capture::read(stream_id)
        }

        /// Close the stream and release the device.
        pub fn close(stream_id: u64) -> Result<(), CameraError> {
            crate::bindings::krate::camera::capture::close(stream_id)
        }
    }
    /// The records and errors this package's interfaces share.
    pub mod types {
        pub use crate::bindings::krate::camera::types::*;
    }
}

/// `krate:speech`: transcription.
pub mod speech {
    /// `krate:speech/transcription`.
    pub mod transcription {
        pub use crate::bindings::krate::speech::transcription::{
            MatchError, SpeechError, Transcript,
        };

        /// Transcribe mono signed 16-bit little-endian PCM with a bundled model.
        pub fn transcribe(
            model_asset: &str,
            pcm_s16_le: &[u8],
            sample_rate: u32,
            language: Option<&str>,
        ) -> Result<Transcript, SpeechError> {
            crate::bindings::krate::speech::transcription::transcribe(
                model_asset,
                pcm_s16_le,
                sample_rate,
                language,
            )
        }

        /// Return a 0 to 100 word-overlap score for one expected script line.
        ///
        /// The transcript stays inside the runtime and the guest receives only a
        /// bounded score.
        pub fn match_line(
            model_asset: &str,
            pcm_s16_le: &[u8],
            sample_rate: u32,
            language: Option<&str>,
            expected: &str,
        ) -> Result<u8, MatchError> {
            crate::bindings::krate::speech::transcription::match_line(
                model_asset,
                pcm_s16_le,
                sample_rate,
                language,
                expected,
            )
        }

        /// Add one bounded audio chunk to the current utterance.
        ///
        /// The runtime owns the growing buffer, so a portable guest does not need a
        /// large allocation. When `finish` is true, the runtime transcribes the
        /// accumulated audio, returns its match score, and clears the utterance.
        pub fn match_line_stream(
            model_asset: &str,
            pcm_s16_le: &[u8],
            sample_rate: u32,
            language: Option<&str>,
            expected: &str,
            finish: bool,
        ) -> Result<Option<u8>, MatchError> {
            crate::bindings::krate::speech::transcription::match_line_stream(
                model_asset,
                pcm_s16_le,
                sample_rate,
                language,
                expected,
                finish,
            )
        }
    }
}
