[package]
name = "krate-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
krate-bundle = { path = "../bundle" }
krate-manifest = { path = "../manifest" }
krate-policy = { path = "../policy" }
krate-runtime = { path = "../runtime" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
wasmparser.workspace = true
wit-parser.workspace = true
tempfile = { workspace = true }
