//! Generate the list of interfaces Krate actually defines (IC-210).
//!
//! The import check used to accept any name starting with `krate:`, so an
//! invented `krate:anything/not-real@999.0.0` passed as a Krate API and the
//! component only failed later, at instantiate, with wasmparser's words. A
//! name in our namespace that we never defined is not a Krate API; it is a
//! component asking for something that does not exist.
//!
//! The list is GENERATED from `wit/` rather than written by hand, because a
//! hand-kept copy drifts the moment an interface is added and then rejects a
//! legitimate app. Every `interface` in every `krate:*` package under the
//! WIT deps is included, which is what a component may genuinely import --
//! including the `types` interfaces that never appear in a world but that
//! every real app pulls in transitively.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn main() {
    let root = workspace_root();
    let wit = root.join("wit");
    println!("cargo:rerun-if-changed={}", wit.display());

    let mut names = BTreeSet::new();
    collect(&wit, &mut names);

    // No WIT tree (a vendored build, a published crate) leaves the list
    // empty, and an empty list must not mean "reject everything". The
    // consumer treats empty as "cannot check", which is the honest reading:
    // we do not know what is defined, so we do not claim a name is invented.
    let entries: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
    let generated = format!(
        "/// Interfaces the Krate WIT defines. Generated by build.rs.\n\
         pub const KNOWN_KRATE_INTERFACES: &[&str] = &[{}];\n",
        entries.join(", ")
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out.join("known_interfaces.rs"), generated)
        .expect("write the generated interface list");
}

/// Every `package krate:x@v` plus each `interface y` it declares.
fn collect(dir: &Path, names: &mut BTreeSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, names);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("wit") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Some((package, version)) = package_of(&text) else {
            continue;
        };
        for line in text.lines() {
            let line = line.trim_start();
            if let Some(rest) = line.strip_prefix("interface ") {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == '-')
                    .collect();
                if !name.is_empty() {
                    names.insert(format!("{package}/{name}@{version}"));
                }
            }
        }
    }
}

/// `package krate:io@0.1.0;` -> ("krate:io", "0.1.0")
fn package_of(text: &str) -> Option<(String, String)> {
    // Scan for the package line rather than demanding it first: a WIT file
    // opens with its doc comments, and returning None on the first line that
    // is not `package` would find nothing at all.
    for line in text.lines() {
        let line = line.trim_start();
        let Some(rest) = line.strip_prefix("package ") else {
            continue;
        };
        if !rest.starts_with("krate:") {
            continue;
        }
        let rest = rest.trim_end_matches(';').trim().trim_end_matches(';');
        if let Some((name, version)) = rest.split_once('@') {
            return Some((name.to_string(), version.trim_end_matches(';').to_string()));
        }
    }
    None
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is crates/bundle; the WIT lives two levels up.
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or(manifest)
}
