//! Generate the list of interfaces Krate actually defines (IC-210).
//!
//! The import check used to accept any name starting with `krate:`, so an
//! invented `krate:anything/not-real@999.0.0` passed as a Krate API and the
//! component only failed later, at instantiate, with wasmparser's words. A
//! name in our namespace that we never defined is not a Krate API; it is a
//! component asking for something that does not exist.
//!
//! The list is GENERATED from `wit/` rather than written by hand, because a
//! hand-kept copy drifts the moment an interface is added and then rejects a
//! legitimate app. Every `interface` in every `krate:*` package under the
//! WIT deps is included, which is what a component may genuinely import --
//! including the `types` interfaces that never appear in a world but that
//! every real app pulls in transitively.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

fn main() {
    let root = workspace_root();
    let wit = root.join("wit");
    println!("cargo:rerun-if-changed={}", wit.display());

    let mut names = BTreeSet::new();
    let mut worlds = BTreeMap::new();
    let mut digest = Sha256::new();
    collect(&wit, &wit, &mut names, &mut worlds, &mut digest);

    // No WIT tree (a vendored build, a published crate) leaves the list
    // empty, and an empty list must not mean "reject everything". The
    // consumer treats empty as "cannot check", which is the honest reading:
    // we do not know what is defined, so we do not claim a name is invented.
    let entries: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
    // Each world and the interfaces it imports, so a component can be
    // checked against the world its manifest declares rather than against
    // "anything Krate defines" (IC-210). A CLI app that imports krate:ui is
    // a GUI app with the wrong manifest, and the linker would say so only
    // at the recipient's machine.
    let world_entries: Vec<String> = worlds
        .iter()
        .map(|(world, imports)| {
            let list: Vec<String> = imports.iter().map(|i| format!("{i:?}")).collect();
            format!("({world:?}, &[{}])", list.join(", "))
        })
        .collect();
    // The identity of the WIT this validator was built from, so a report
    // can say which contract it checked against. Empty when there is no WIT.
    let wit_digest = if names.is_empty() {
        String::new()
    } else {
        format!("{:x}", digest.finalize())
    };
    let generated = format!(
        "/// Interfaces the Krate WIT defines. Generated by build.rs.\n\
         pub const KNOWN_KRATE_INTERFACES: &[&str] = &[{}];\n\
         /// Every world and the interfaces it imports. Generated by build.rs.\n\
         pub const KNOWN_WORLDS: &[(&str, &[&str])] = &[{}];\n\
         /// SHA-256 over the WIT tree this list came from. Generated by build.rs.\n\
         pub const WIT_DIGEST: &str = {:?};\n",
        entries.join(", "),
        world_entries.join(", "),
        wit_digest,
    );
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out.join("known_interfaces.rs"), generated)
        .expect("write the generated interface list");
}

/// Every `package krate:x@v` plus each `interface y` it declares; every
/// `world w` with the `import` lines inside it; and a digest over every
/// .wit file's bytes, in path order, so the same tree always hashes the same.
fn collect(
    root: &Path,
    dir: &Path,
    names: &mut BTreeSet<String>,
    worlds: &mut BTreeMap<String, BTreeSet<String>>,
    digest: &mut Sha256,
) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    // Sorted, so the digest does not depend on the order a filesystem
    // happens to list a directory in.
    let mut paths: Vec<PathBuf> = entries.flatten().map(|e| e.path()).collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            collect(root, &path, names, worlds, digest);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("wit") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        let relative = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        digest.update(relative.as_bytes());
        digest.update(b"\0");
        digest.update(text.as_bytes());
        digest.update(b"\0");
        let Some((package, version)) = package_of(&text) else {
            continue;
        };
        let mut current_world: Option<String> = None;
        for line in text.lines() {
            let line = line.trim_start();
            if let Some(rest) = line.strip_prefix("interface ") {
                let name = ident(rest);
                if !name.is_empty() {
                    names.insert(format!("{package}/{name}@{version}"));
                }
            } else if let Some(rest) = line.strip_prefix("world ") {
                let name = ident(rest);
                if !name.is_empty() {
                    let world = format!("{package}/{name}@{version}");
                    worlds.entry(world.clone()).or_default();
                    current_world = Some(world);
                }
            } else if let (Some(world), Some(rest)) = (&current_world, line.strip_prefix("import "))
            {
                let import = rest.trim_end_matches(';').trim();
                if import.starts_with("krate:") {
                    worlds
                        .entry(world.clone())
                        .or_default()
                        .insert(import.to_string());
                }
            } else if line.starts_with('}') {
                current_world = None;
            }
        }
    }
}

/// The identifier at the start of `rest`: lowercase, digits and dashes.
fn ident(rest: &str) -> String {
    rest.chars()
        .take_while(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == '-')
        .collect()
}

/// `package krate:io@0.1.0;` -> ("krate:io", "0.1.0")
fn package_of(text: &str) -> Option<(String, String)> {
    // Scan for the package line rather than demanding it first: a WIT file
    // opens with its doc comments, and returning None on the first line that
    // is not `package` would find nothing at all.
    for line in text.lines() {
        let line = line.trim_start();
        let Some(rest) = line.strip_prefix("package ") else {
            continue;
        };
        if !rest.starts_with("krate:") {
            continue;
        }
        let rest = rest.trim_end_matches(';').trim().trim_end_matches(';');
        if let Some((name, version)) = rest.split_once('@') {
            return Some((name.to_string(), version.trim_end_matches(';').to_string()));
        }
    }
    None
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is crates/bundle; the WIT lives two levels up.
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or(manifest)
}
