#!/usr/bin/env python3
"""Write the FAQ page's FAQPage structured data from the questions on the page.

docs/landing/faq/index.html is the source: every <details> with a <summary>
is one question, and its answer is the <div class="ans"> inside it. This
script turns those into the JSON-LD block between the faq-schema markers in
the page's <head>, so what search engines and AI answer tools read is exactly
what a person reads. Never edit the block by hand.

  python3 scripts/build-faq-schema.py               rewrite the block
  python3 scripts/build-faq-schema.py --check       exit 1 if the block is stale
  python3 scripts/build-faq-schema.py --self-test   prove the parse and the check
"""
import html
import json
import re
import sys
from pathlib import Path

PAGE = Path(__file__).resolve().parent.parent / "docs" / "landing" / "faq" / "index.html"
SITE = "https://krate.tech"
START = "<!-- faq-schema:start (generated by scripts/build-faq-schema.py) -->"
END = "<!-- faq-schema:end -->"
QA = re.compile(
    r'<details[^>]*><summary>(?:<span class="n">\d+</span>)?(.*?)</summary>'
    r'<div class="ans">(.*?)</div></details>', re.S)
# Google renders these tags in an FAQ answer; everything else is unwrapped.
KEEP = {"p", "a", "b", "strong", "i", "em", "br", "ul", "ol", "li"}


def answer_html(raw):
    def tag(m):
        closing, name, attrs = m.group(1), m.group(2).lower(), m.group(3)
        if name not in KEEP:
            return ""
        if name == "a" and not closing:
            href = re.search(r'href="([^"]+)"', attrs)
            url = href.group(1) if href else ""
            if url.startswith("/"):
                url = SITE + url
            return f'<a href="{url}">'
        return f"</{name}>" if closing else f"<{name}>"
    out = re.sub(r"<(/?)([a-zA-Z0-9]+)([^>]*)>", tag, raw)
    return html.unescape(out).strip()


def questions(page_text):
    out = []
    for q, a in QA.findall(page_text):
        name = html.unescape(re.sub(r"<[^>]+>", "", q)).strip()
        out.append((name, answer_html(a)))
    return out


def block(page_text):
    data = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in questions(page_text)
        ],
    }
    body = json.dumps(data, ensure_ascii=False, indent=1).replace("</", "<\\/")
    return f'{START}\n<script type="application/ld+json">\n{body}\n</script>\n{END}'


def render(page_text):
    new = block(page_text)
    if START in page_text:
        a = page_text.index(START)
        b = page_text.index(END, a) + len(END)
        return page_text[:a] + new + page_text[b:]
    return page_text.replace("</head>", new + "\n</head>", 1)


def self_test():
    page = ('<html><head></head><body>'
            '<details id="x" open><summary><span class="n">01</span>Why &amp; how?</summary>'
            '<div class="ans"><p>Use <code class="k">krate</code>, see <a href="/docs/">docs</a>.</p></div></details>'
            '<details><summary><span class="n">02</span>Second?</summary><div class="ans"><p>Yes.</p></div></details>'
            '</body></html>')
    qs = questions(page)
    assert qs[0][0] == "Why & how?", qs
    assert qs[0][1] == '<p>Use krate, see <a href="https://krate.tech/docs/">docs</a>.</p>', qs[0][1]
    assert len(qs) == 2
    once = render(page)
    assert render(once) == once, "rendering twice must change nothing"
    data = json.loads(once.split('ld+json">')[1].split("</script>")[0])
    assert len(data["mainEntity"]) == 2
    # A changed answer must make the check fail.
    edited = once.replace("<p>Yes.</p>", "<p>No.</p>")
    assert render(edited) != edited, "a stale block must be detected"
    print("self-test passed")


def main():
    if "--self-test" in sys.argv:
        self_test()
        return 0
    text = PAGE.read_text(encoding="utf-8")
    new = render(text)
    n = len(questions(text))
    if "--check" in sys.argv:
        if new != text:
            print("faq/index.html: the FAQPage data is stale; run python3 scripts/build-faq-schema.py")
            return 1
        print(f"FAQPage data matches the page ({n} questions)")
        return 0
    PAGE.write_text(new, encoding="utf-8")
    print(f"wrote FAQPage data for {n} questions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
