#!/usr/bin/env sh
# The checked-in generated bindings are the ones the pinned generator
# produces (IC-295).
#
# Every */src/bindings.rs in this repository is wit-bindgen output, and
# `cargo component build` rewrites it on every build. When the checked-in
# copy was made by a different generator version, every build dirties the
# tree: 43 files and 325,000 lines of churn on this machine, a `git status`
# nobody could read, and the commit-stamp test calling a clean checkout
# dirty (K-282). The remedy is not to stop the generator -- cargo-component
# has no such switch -- but to keep the committed copy equal to what it
# generates, so a build changes nothing.
#
# `cargo component bindings` is the explicit refresh: it regenerates without
# compiling. This runs it everywhere bindings live and fails if anything
# moved, naming the directories. The fix is to run it and commit -- a
# binding refresh as its own reviewed change, separate from ordinary
# compilation -- or, if the generator version differs from the one CI pins,
# to install that one.
#
#   scripts/check-bindings-fresh.sh          # check
#   scripts/check-bindings-fresh.sh --fix    # regenerate and leave the diff for review
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

PINNED="0.21.1"
have="$(cargo component --version 2>/dev/null | awk '{print $NF}')"
if [ -z "$have" ]; then
  echo "cargo-component is not installed; install the pinned $PINNED with:" >&2
  echo "  cargo install cargo-component --locked --version $PINNED" >&2
  exit 2
fi
if [ "$have" != "$PINNED" ]; then
  echo "cargo-component $have is installed but CI pins $PINNED; the bindings it" >&2
  echo "generates may differ. Install the pinned one before trusting this check:" >&2
  echo "  cargo install cargo-component --locked --version $PINNED" >&2
  exit 2
fi

# Only tracked bindings: an app somebody is still drafting is not ours to judge.
dirs="$(git ls-files '*/src/bindings.rs' | sed 's#/src/bindings.rs$##' | sort -u)"
if git diff --quiet -- '*/src/bindings.rs'; then
  :
else
  echo "bindings were already modified before this check ran; commit or revert them first:" >&2
  git diff --stat -- '*/src/bindings.rs' >&2
  exit 2
fi

count=0
for dir in $dirs; do
  [ -f "$dir/Cargo.toml" ] || continue
  # crates/bindings-rust is the SDK's own binding, generated by its own
  # step, not by cargo-component against an app's manifest.
  case "$dir" in crates/*) continue ;; esac
  count=$((count + 1))
  (cd "$dir" && cargo component bindings >/dev/null 2>&1) || {
    echo "cargo component bindings failed in $dir" >&2
    exit 1
  }
done

if git diff --quiet -- '*/src/bindings.rs'; then
  echo "OK -- the checked-in bindings match what cargo-component $PINNED generates ($count packages)."
  exit 0
fi

if [ "${1:-}" = "--fix" ]; then
  echo "regenerated; review and commit as a binding refresh:"
  git diff --stat -- '*/src/bindings.rs'
  exit 0
fi

echo "the checked-in bindings are not what cargo-component $PINNED generates:" >&2
git diff --stat -- '*/src/bindings.rs' >&2
echo >&2
echo "Every build rewrites these, so a stale copy dirties the tree on every build." >&2
echo "Refresh them as their own change: scripts/check-bindings-fresh.sh --fix, then commit." >&2
git checkout -- '*/src/bindings.rs'
exit 1
