#!/usr/bin/env python3
"""The developer-control review, and the check that it covers every public
boundary (IC-175, IC-176; the CP1 exit test).

Krate enforces a boundary only where portability, the recipient's
permission, OS safety, evidence, the platform, or the law requires it.
Everything else is the application's choice. The review in
docs/developer-control/review.json says, for every public boundary -- every
WIT interface Krate declares, the file format, the identity rules, the hub,
Studio, the runtime's limits -- what Krate standardizes, what stays the
developer's, and the lower-level interface that preserves that choice. A
boundary that is compulsory names its justification from that fixed list,
or records the gap in so many words. A compulsory boundary with neither is
what IC-175 calls an unjustified restriction, and this check refuses it.

    python3 scripts/developer-control-review.py            # write docs/developer-control-review.md
    python3 scripts/developer-control-review.py --check    # fail if a WIT interface is unreviewed, an entry is stale, or the doc drifted
    python3 scripts/developer-control-review.py --self-test
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVIEW = ROOT / "docs/developer-control/review.json"
DOC = ROOT / "docs/developer-control-review.md"
WIT_ROOT = ROOT / "wit/krate"
SCHEMA = "krate.developer-control-review.v1"
KINDS = {"wit", "format", "identity", "service", "workflow", "runtime"}
FIELDS = ("standardizes", "application_choice", "escape_hatch")


def wit_interfaces(wit_root=WIT_ROOT):
    """Every `package/interface` declared under wit_root, from the files."""
    found = set()
    for path in sorted(wit_root.rglob("*.wit")):
        text = path.read_text()
        package = re.search(r"^package\s+([^;\s]+)\s*;", text, re.M)
        if not package:
            continue
        for name in re.findall(r"^interface\s+([a-z0-9-]+)\s*\{", text, re.M):
            found.add(f"{package.group(1)}/{name}")
    return found


def problems(review, interfaces):
    """Why the review is not complete or not honest. Empty means it is."""
    p = []
    if review.get("schema") != SCHEMA:
        p.append(f"schema must be {SCHEMA}")
    justifications = set((review.get("justifications") or {}).keys())
    if not justifications:
        p.append("the review must name its justification classes")
    seen = set()
    reviewed_wit = set()
    for entry in review.get("boundaries") or []:
        ident = entry.get("id", "?")
        pre = f"{ident}"
        if entry.get("kind") not in KINDS:
            p.append(f"{pre}: kind must be one of {sorted(KINDS)}")
        if ident in seen:
            p.append(f"{pre}: reviewed twice")
        seen.add(ident)
        for field in FIELDS:
            value = entry.get(field)
            if not isinstance(value, str) or not value.strip():
                p.append(f"{pre}: {field} must be said, in words")
        if "compulsory" not in entry or not isinstance(entry["compulsory"], bool):
            p.append(f"{pre}: compulsory must be true or false")
        elif entry["compulsory"]:
            j = entry.get("justification")
            gap = entry.get("gap")
            if j not in justifications and not (isinstance(gap, str) and gap.strip()):
                p.append(f"{pre}: a compulsory boundary must name a justification from {sorted(justifications)} or record its gap -- an unjustified restriction is refused (IC-175)")
            if j is not None and j not in justifications:
                p.append(f"{pre}: justification {j!r} is not one of {sorted(justifications)}")
        else:
            if entry.get("justification") is not None:
                p.append(f"{pre}: a boundary that is not compulsory needs no justification; remove it or make the boundary compulsory")
        if entry.get("kind") == "wit":
            reviewed_wit.add(ident)
            if ident not in interfaces:
                p.append(f"{pre}: reviewed, but no such interface is declared under wit/krate (stale)")
    for missing in sorted(interfaces - reviewed_wit):
        p.append(f"{missing}: declared under wit/krate and not reviewed -- every public boundary must be (IC-175)")
    return p


def render(review, interfaces):
    boundaries = review.get("boundaries") or []
    lines = [
        "# Developer-control review",
        "",
        "<!-- Generated by scripts/developer-control-review.py from docs/developer-control/review.json. Edit the JSON, then run the script. CI checks that every WIT interface is reviewed and that this file matches. -->",
        "",
        review.get("principle", ""),
        "",
        "## Justification classes",
        "",
    ]
    for name, why in sorted((review.get("justifications") or {}).items()):
        lines.append(f"- **{name}**: {why}")
    compulsory = [b for b in boundaries if b.get("compulsory")]
    gaps = [b for b in boundaries if b.get("gap")]
    lines += [
        "",
        "## Summary",
        "",
        f"- {len(boundaries)} boundaries reviewed, {len([b for b in boundaries if b.get('kind') == 'wit'])} of them WIT interfaces ({len(interfaces)} declared under wit/krate).",
        f"- {len(compulsory)} compulsory, each with a justification or a recorded gap; {len(boundaries) - len(compulsory)} optional.",
        f"- {len(gaps)} recorded gaps where the escape hatch does not yet exist or the boundary is narrower than a developer would want.",
        "",
        "## Every boundary",
        "",
        "| Boundary | Kind | Krate standardizes | The application chooses | The lower-level way | Compulsory | Why |",
        "|---|---|---|---|---|---|---|",
    ]
    order = {"wit": 0, "format": 1, "identity": 2, "service": 3, "workflow": 4, "runtime": 5}
    for b in sorted(boundaries, key=lambda b: (order.get(b.get("kind"), 9), b.get("id", ""))):
        why = b.get("justification") or ("--" if not b.get("compulsory") else "GAP")
        lines.append(
            f"| `{b.get('id')}` | {b.get('kind')} | {_cell(b.get('standardizes'))} | {_cell(b.get('application_choice'))} | "
            f"{_cell(b.get('escape_hatch'))} | {'yes' if b.get('compulsory') else 'no'} | {why} |"
        )
    if gaps:
        lines += ["", "## Gaps", "", "Where a developer's choice is narrower than the principle says it should be. Each is a row above with a gap recorded; none is a rule Krate defends.", ""]
        for b in sorted(gaps, key=lambda b: b.get("id", "")):
            lines.append(f"- `{b.get('id')}`: {b.get('gap')}")
    return "\n".join(lines) + "\n"


def _cell(text):
    return str(text or "").replace("|", "\\|").replace("\n", " ")


def load(path=REVIEW):
    return json.loads(Path(path).read_text())


def cmd_write():
    review = load()
    interfaces = wit_interfaces()
    found = problems(review, interfaces)
    for f in found:
        print(f"FAIL: {f}", file=sys.stderr)
    if found:
        return 1
    DOC.write_text(render(review, interfaces))
    print(f"wrote {DOC.relative_to(ROOT)}: {len(review['boundaries'])} boundaries, {len(interfaces)} WIT interfaces covered")
    return 0


def cmd_check():
    review = load()
    interfaces = wit_interfaces()
    found = problems(review, interfaces)
    if not found and DOC.read_text() != render(review, interfaces):
        found.append(f"{DOC.relative_to(ROOT)} does not match the review; run scripts/developer-control-review.py and commit it")
    for f in found:
        print(f"FAIL: {f}", file=sys.stderr)
    if found:
        return 1
    print(f"OK -- every one of {len(interfaces)} WIT interfaces and {len(review['boundaries']) - len(interfaces)} other boundaries is reviewed, every compulsory one is justified or its gap recorded, and the doc matches")
    return 0


def self_test():
    import tempfile
    failures = []

    def check(name, cond, detail=""):
        if not cond:
            failures.append(f"{name}: {detail}" if detail else name)

    with tempfile.TemporaryDirectory() as tmp:
        wit = Path(tmp) / "wit"
        (wit / "net").mkdir(parents=True)
        (wit / "net" / "net.wit").write_text("package krate:net@0.1.0;\n\ninterface types {\n}\n\n/// docs\ninterface http-client {\n  foo: func();\n}\n")
        (wit / "world.wit").write_text("package krate:app@0.1.0;\nworld cli {\n  import krate:net/http-client@0.1.0;\n}\n")
        found = wit_interfaces(wit)
        check("interfaces are read from the files", found == {"krate:net@0.1.0/types", "krate:net@0.1.0/http-client"}, str(found))

        def entry(**over):
            base = {"kind": "wit", "id": "krate:net@0.1.0/http-client", "standardizes": "the grant boundary",
                    "application_choice": "the protocol", "escape_hatch": "raw bytes", "compulsory": True,
                    "justification": "recipient-permission"}
            base.update(over)
            return base

        types = entry(id="krate:net@0.1.0/types", justification="portability")
        good = {"schema": SCHEMA, "principle": "developer control by default",
                "justifications": {"portability": "p", "recipient-permission": "r"},
                "boundaries": [types, entry(), {"kind": "format", "id": "the archive", "standardizes": "one container",
                                                "application_choice": "contents", "escape_hatch": "unknown entries survive",
                                                "compulsory": True, "justification": "portability"}]}
        check("a complete, justified review passes", problems(good, found) == [], str(problems(good, found)))

        missing = dict(good, boundaries=[types])
        p = problems(missing, found)
        check("an unreviewed interface is refused", any("not reviewed" in x and "http-client" in x for x in p), str(p))

        stale = dict(good, boundaries=good["boundaries"] + [entry(id="krate:net@0.1.0/sockets")])
        p = problems(stale, found)
        check("an entry for an interface that does not exist is refused", any("stale" in x for x in p), str(p))

        unjustified = dict(good, boundaries=[types, entry(justification=None)] + good["boundaries"][2:])
        p = problems(unjustified, found)
        check("a compulsory boundary with no justification and no gap is refused", any("unjustified" in x for x in p), str(p))
        with_gap = dict(good, boundaries=[types, entry(justification=None, gap="no socket primitive yet")] + good["boundaries"][2:])
        check("a compulsory boundary with a recorded gap passes", problems(with_gap, found) == [], str(problems(with_gap, found)))
        odd = dict(good, boundaries=[types, entry(justification="because")] + good["boundaries"][2:])
        p = problems(odd, found)
        check("a justification outside the fixed list is refused", any("not one of" in x for x in p), str(p))
        optional_justified = dict(good, boundaries=[types, entry(compulsory=False)] + good["boundaries"][2:])
        p = problems(optional_justified, found)
        check("an optional boundary carrying a justification is refused as confused", any("needs no justification" in x for x in p), str(p))
        for field in FIELDS:
            blank = dict(good, boundaries=[types, entry(**{field: ""})] + good["boundaries"][2:])
            p = problems(blank, found)
            check(f"an empty {field} is refused", any(field in x for x in p), str(p))
        twice = dict(good, boundaries=good["boundaries"] + [entry()])
        check("a boundary reviewed twice is refused", any("twice" in x for x in problems(twice, found)))

        doc = render(good, found)
        check("the doc names every boundary", all(b["id"] in doc for b in good["boundaries"]))
        check("the doc lists gaps when there are any", "## Gaps" in render(with_gap, found) and "no socket primitive" in render(with_gap, found))
        check("and not when there are none", "## Gaps" not in doc)
        check("rendering is stable", render(good, found) == doc)

    if failures:
        print("developer-control-review self-test FAILED:\n")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("developer-control-review self-test OK -- interfaces are read from the WIT files, an unreviewed or stale interface is refused, a compulsory boundary must be justified or its gap recorded, and the doc is rendered from the review")
    return 0


def main(argv):
    if "--self-test" in argv:
        return self_test()
    if "--check" in argv:
        return cmd_check()
    return cmd_write()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
