#!/usr/bin/env sh
# Re-measure the apps the reports page compares Krate against.
#
# Those sizes are recorded in scripts/build-reports-page.py rather than measured
# every time, because the page is regenerated by CI on a Linux runner where
# /Applications does not exist -- a live `du` there silently dropped the whole
# comparison from the published page.
#
# Recorded numbers rot. Run this on a Mac when the apps have updated, and paste
# the result into PEERS.
#
#   sh scripts/measure-peer-apps.sh

set -eu

printf 'PEERS = [\n'
for app in "Visual Studio Code" "Discord" "Spotify" "Slack" "Notion"; do
  path="/Applications/$app.app"
  [ -d "$path" ] || continue
  kb=$(du -sk "$path" | cut -f1)
  # Printed in the exact form the generator expects, so updating it is a paste
  # rather than a transcription -- transcription is where a digit goes missing.
  # Grouped with awk rather than sed: the sed idiom for this is a GNU
  # extension, and BSD sed on macOS rejects it -- which is exactly the machine
  # this script has to run on.
  grouped=$(printf '%s' "$kb" | awk '{
    n = $0; out = ""
    while (length(n) > 3) {
      out = "_" substr(n, length(n) - 2) out
      n = substr(n, 1, length(n) - 3)
    }
    print n out
  }')
  printf '    ("%s", "Electron", %s * 1024),\n' "$app" "$grouped"
done
printf ']\n'

printf '\nMeasured %s on %s.\n' "$(date +%Y-%m-%d)" "$(uname -sm)"
printf 'Paste the block above into PEERS in scripts/build-reports-page.py,\n'
printf 'and update the date in the comment above it.\n'
