#!/usr/bin/env sh
# Keep the advisory scan as evidence, not as a passing exit code (IC-568).
#
#     scripts/record-advisory-evidence.sh [--check]
#
# `cargo deny check advisories` answers one question -- is anything matched
# right now -- and then throws the answer away. That is not enough to release
# on. What a release needs to show is which advisories matched, which path
# brings each one in, whether it is reachable, who decided that, and when the
# question was last asked.
#
# So this writes evidence/advisories/latest.md and a dated copy beside it. It
# does not replace scripts/check-dependencies.sh, which is the gate; this is
# the record of what the gate saw.
#
# --check re-runs the scan and fails if the stored record is stale against it,
# which is what turns "we looked once" into "we look every time".
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT="$ROOT/evidence/advisories"
TODAY="$(date -u +%Y-%m-%d)"
SCANNED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$OUT"

scan="$(mktemp)"
tree="$(mktemp)"
cleanup() { rm -f "$scan" "$tree"; }
trap cleanup EXIT

cd "$ROOT"

# The scan itself. A non-zero exit is kept, not swallowed: a record that reads
# "ok" because the scanner fell over is worse than no record.
if cargo deny check advisories >"$scan" 2>&1; then
  verdict="ok"
  status=0
else
  status="$?"
  verdict="matched"
fi

# Every advisory the config chooses to ignore, with the reason the config
# itself gives. An ignore is a decision that was made, not an absence.
ignored="$(sed -n '/^\[advisories\]/,/^\[/p' deny.toml \
  | grep -oE '"RUSTSEC-[0-9]{4}-[0-9]{4}"' \
  | tr -d '"' || true)"

{
  echo "# Advisory scan"
  echo
  echo "Scanned: $SCANNED_AT"
  echo "Commit:  $(git rev-parse HEAD)"
  echo "Scanner: $(cargo deny --version 2>/dev/null || echo 'cargo-deny (version unavailable)')"
  echo "Verdict: $verdict"
  echo
  echo "Generated by scripts/record-advisory-evidence.sh. Do not hand-edit:"
  echo "a record that disagrees with the scanner is worse than none."
  echo
  echo "## What the scanner said"
  echo
  echo '```'
  cat "$scan"
  echo '```'
  echo

  if [ -n "$ignored" ]; then
    echo "## Accepted matches, and why each one is not reachable"
    echo
    echo "An ignored advisory is a decision. Each one below names the path that"
    echo "brings it in, so the reasoning can be checked rather than trusted."
    echo
    for id in $ignored; do
      echo "### $id"
      echo
      echo "Reason recorded in deny.toml:"
      echo
      sed -n "/^\[advisories\]/,/^\[licenses\]/p" deny.toml \
        | awk -v id="$id" '
            /^[[:space:]]*#/ { buf = buf substr($0, index($0,"#")+1) "\n"; next }
            index($0, id)    { printf "%s", buf; exit }
            { buf = "" }
          ' | sed 's/^[[:space:]]*/    /'
      echo
      # The crate the advisory is about, and every path to it. `--target all`
      # matters: the camera backend is Windows/Linux only, so a host-only tree
      # prints nothing and would read as "not a dependency".
      echo "Dependency path (\`cargo tree -i <crate> --target all\`):"
      echo
      echo '```'
      case "$id" in
        RUSTSEC-2024-0436) pkg=paste ;;
        *)                 pkg="" ;;
      esac
      if [ -n "$pkg" ]; then
        # The checkout path is stripped: it differs on every machine and CI
        # runner, and a record that churns on where it was generated is a
        # record nobody can diff.
        cargo tree -i "$pkg" --workspace --target all -e normal,build 2>&1 \
          | sed "s#(${ROOT}#(#" \
          | sed 's/^/    /' || echo "    (path unavailable)"
      else
        echo "    (no crate mapping recorded for $id -- add one to this script)"
      fi
      echo '```'
      echo
    done
  else
    echo "## Accepted matches"
    echo
    echo "None. Nothing is ignored, so the scan above is the whole picture."
    echo
  fi

  echo "## What this does not tell you"
  echo
  echo "A clean scan means no advisory matched a crate in the graph today. It"
  echo "is not a statement that the code is free of defects, and it goes stale"
  echo "the moment the advisory database moves -- which is why the scan is"
  echo "dated and re-run rather than filed once."
} > "$OUT/latest.md"

cp "$OUT/latest.md" "$OUT/$TODAY.md"

echo "Wrote $OUT/latest.md and $OUT/$TODAY.md (verdict: $verdict)"

# In --check mode the scan's own result is the gate, so a matched advisory
# fails here too rather than being recorded and shrugged at.
if [ "${1:-}" = "--check" ] && [ "$status" != "0" ]; then
  echo "advisory scan failed; see $OUT/latest.md" >&2
  exit "$status"
fi
