#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

OUTPUT="target/phase2-go-readiness-evidence/go-readiness-evidence.md"
STRICT="${KRATE_GO_READINESS_EVIDENCE_STRICT:-0}"
MODE="${KRATE_GO_VARIANT_SMOKE_MODE:-required}"

usage() {
  cat <<'USAGE'
Usage: scripts/record-phase2-go-readiness-evidence.sh [--strict] [--mode <mode>] [--output <path>]

Options:
  --strict           Exit non-zero when Go build or import-purity checks fail
  --mode <mode>      optional|required for TinyGo smoke build (default: required)
  --output <path>    Output markdown file path

Environment:
  KRATE_GO_READINESS_EVIDENCE_STRICT   1 to fail on build/import-purity errors
  KRATE_GO_VARIANT_SMOKE_MODE          optional|required

Notes:
  - The script always writes a markdown report.
  - Import purity means every component import starts with krate:.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT="1"
      shift
      ;;
    --mode)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --mode" >&2
        usage
        exit 2
      fi
      MODE="$2"
      shift 2
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "missing value for --output" >&2
        usage
        exit 2
      fi
      OUTPUT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      if [ "$OUTPUT" = "target/phase2-go-readiness-evidence/go-readiness-evidence.md" ]; then
        OUTPUT="$1"
        shift
      else
        echo "unknown argument: $1" >&2
        usage
        exit 2
      fi
      ;;
  esac
done

case "$MODE" in
  optional|required)
    ;;
  *)
    echo "Go readiness evidence error: unknown mode '$MODE'." >&2
    echo "Allowed values: optional, required" >&2
    exit 2
    ;;
esac

if [ -d "$HOME/.cargo/bin" ]; then
  PATH="$HOME/.cargo/bin:$PATH"
  export PATH
fi

mkdir -p "$(dirname "$OUTPUT")"
TMP_DIR="target/phase2-go-readiness-evidence/.tmp"
mkdir -p "$TMP_DIR"
BUILD_LOG="$TMP_DIR/build.log"
IMPORT_LOG="$TMP_DIR/imports.log"
SMOKE_DIR="$ROOT/$TMP_DIR/smoke"

if KRATE_GO_VARIANT_SMOKE_MODE="$MODE" KRATE_GO_VARIANT_SMOKE_OUT_DIR="$SMOKE_DIR" scripts/build-phase2-go-variant-smoke.sh >"$BUILD_LOG" 2>&1; then
  BUILD_CODE=0
else
  BUILD_CODE=$?
fi

clock="$SMOKE_DIR/krate_go_clock_wasip2.wasm"
cat="$SMOKE_DIR/krate_go_cat_wasip2.wasm"
curl="$SMOKE_DIR/krate_go_curl_wasip2.wasm"

if [ "$BUILD_CODE" -eq 0 ] && [ -f "$clock" ] && [ -f "$cat" ] && [ -f "$curl" ]; then
  if scripts/check-component-imports.sh "$clock" "$cat" "$curl" >"$IMPORT_LOG" 2>&1; then
    IMPORT_CODE=0
  else
    IMPORT_CODE=$?
  fi
else
  IMPORT_CODE=127
  {
    echo "Import-purity check skipped because the TinyGo smoke build did not produce all artifacts."
    echo
    echo "Expected:"
    echo "- $clock"
    echo "- $cat"
    echo "- $curl"
  } >"$IMPORT_LOG"
fi

now_utc="$(date -u +%FT%TZ)"
host_os="$(uname -s 2>/dev/null || printf 'unknown')"
host_arch="$(uname -m 2>/dev/null || printf 'unknown')"
git_commit="$(git rev-parse --short HEAD 2>/dev/null || printf 'unknown')"
tinygo_version="$(tinygo version 2>/dev/null || printf 'not found')"
go_version="$(go version 2>/dev/null || printf 'not found')"
wasm_tools_version="$(wasm-tools --version 2>/dev/null || printf 'not found')"

result_of() {
  code="$1"
  if [ "$code" -eq 0 ]; then
    printf 'passed'
  elif [ "$code" -eq 127 ]; then
    printf 'skipped'
  else
    printf 'failed'
  fi
}

exists_of() {
  path="$1"
  if [ -f "$path" ]; then
    printf 'yes'
  else
    printf 'no'
  fi
}

hash_of() {
  path="$1"
  if [ -f "$path" ]; then
    shasum -a 256 "$path" | awk '{print $1}'
  else
    printf 'n/a'
  fi
}

status_note="Go runtime fixtures are ready for Phase 2 promotion."
if [ "$BUILD_CODE" -ne 0 ]; then
  status_note="Go smoke artifacts did not build on this host."
elif [ "$IMPORT_CODE" -ne 0 ]; then
  status_note="Go smoke artifacts build, but they are not Krate import-pure yet."
fi

{
  echo "# Phase 2 Go Readiness Evidence"
  echo
  echo "This file is generated by \`scripts/record-phase2-go-readiness-evidence.sh\`."
  echo
  echo "## Summary"
  echo
  echo "$status_note"
  echo
  echo "Phase 2 only promotes Go runtime fixtures when the components import Krate"
  echo "UAPI packages and do not import host \`wasi:*\` APIs directly."
  echo
  echo "## Host"
  echo
  echo "- Git commit: \`$git_commit\`"
  echo "- Host: \`$host_os\` / \`$host_arch\`"
  echo "- Generated at (UTC): \`$now_utc\`"
  echo "- TinyGo smoke mode: \`$MODE\`"
  echo "- TinyGo: \`$tinygo_version\`"
  echo "- Go: \`$go_version\`"
  echo "- wasm-tools: \`$wasm_tools_version\`"
  echo
  echo "## Command Results"
  echo
  echo "| Step | Exit code | Result |"
  echo "|---|---:|---|"
  echo "| Build Go smoke components (\`scripts/build-phase2-go-variant-smoke.sh\`) | $BUILD_CODE | $(result_of "$BUILD_CODE") |"
  echo "| Check Krate import purity (\`scripts/check-component-imports.sh\`) | $IMPORT_CODE | $(result_of "$IMPORT_CODE") |"
  echo
  echo "## Smoke Artifacts"
  echo
  echo "| Artifact | Exists | SHA-256 |"
  echo "|---|---|---|"
  echo "| krate_go_clock_wasip2.wasm | $(exists_of "$clock") | \`$(hash_of "$clock")\` |"
  echo "| krate_go_cat_wasip2.wasm | $(exists_of "$cat") | \`$(hash_of "$cat")\` |"
  echo "| krate_go_curl_wasip2.wasm | $(exists_of "$curl") | \`$(hash_of "$curl")\` |"
  echo
  echo "## Import-Purity Log"
  echo
  echo '```text'
  tail -n 160 "$IMPORT_LOG"
  echo '```'
  echo
  echo "## Build Log"
  echo
  echo '```text'
  tail -n 120 "$BUILD_LOG"
  echo '```'
} >"$OUTPUT"

echo "wrote $OUTPUT"

if [ "$STRICT" = "1" ] && { [ "$BUILD_CODE" -ne 0 ] || [ "$IMPORT_CODE" -ne 0 ]; }; then
  exit 1
fi

exit 0
