#!/usr/bin/env python3
"""The SDK's Phase 3 layer, generated from the gui-world bindings (IC-298,
K-302).

crates/bindings-rust/src/bindings_gui.rs is wit-bindgen's output for the
`gui` world. This reads every function it declares under krate:ui, krate:gfx,
krate:audio, krate:camera and krate:speech, and writes
crates/bindings-rust/src/phase3.rs: one thin, documented wrapper per
function with the exact same signature, and the interface's types
re-exported beside it, so an app reaches `krate::ui::window::create(...)`
through the SDK it already depends on instead of through a generated copy
of the bindings inside the app. The wrappers add nothing and hide nothing:
every WIT state and error reaches the app as the binding lowers it.

    python3 scripts/sdk-phase3-layer.py            # write phase3.rs
    python3 scripts/sdk-phase3-layer.py --check    # fail if phase3.rs is not what the bindings generate
    python3 scripts/sdk-phase3-layer.py --self-test
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BINDINGS = ROOT / "crates/bindings-rust/src/bindings_gui.rs"
OUT = ROOT / "crates/bindings-rust/src/phase3.rs"
PACKAGES = ("ui", "gfx", "audio", "camera", "speech")
HEADER = "// Generated by scripts/sdk-phase3-layer.py from bindings_gui.rs. DO NOT EDIT.\n"


def parse(text):
    """Every `pub fn` and every `pub` type under krate/<package>/<interface>
    in a wit-bindgen output, keyed by `package/interface`. Methods (`&self`)
    are skipped: they belong to the type that is re-exported."""
    lines = text.split("\n")
    stack = []
    depth = 0
    fns = {}
    types = {}
    docs = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        m = re.match(r"^\s*pub mod (\w+)\s*\{", line)
        if m:
            stack.append((m.group(1), depth))
        path = "/".join(name for name, _ in stack)
        parts = path.split("/")
        in_scope = len(parts) == 3 and parts[0] == "krate" and parts[1] in PACKAGES
        comment = stripped.startswith("//")
        if stripped.startswith("///"):
            docs.append(stripped[3:].strip())
        elif not comment:
            m = re.match(r"^\s*pub fn (\w+)\((.*)$", line)
            if m and in_scope:
                sig = stripped
                j = i
                # The signature ends at the first `{` past the argument list's
                # closing paren; a one-line method body (`{ "" }`) must not
                # pull the next function into it.
                def body_at(text):
                    start = text.index("(")
                    depth = 0
                    for k in range(start, len(text)):
                        if text[k] == "(":
                            depth += 1
                        elif text[k] == ")":
                            depth -= 1
                            if depth == 0:
                                brace = text.find("{", k)
                                return brace
                    return -1
                while body_at(sig) < 0 and j + 1 < len(lines):
                    j += 1
                    sig += " " + lines[j].strip()
                sig = sig[: body_at(sig)].strip()
                if "&self" not in sig and "self," not in sig:
                    fns.setdefault(path, []).append((m.group(1), sig, list(docs)))
                # the braces of the joined lines are counted once, below
                depth += sum(l.count("{") - l.count("}") for l in lines[i + 1 : j + 1])
                i = j
            m = re.match(r"^\s*pub (?:struct|enum|type) (\w+)", line)
            if m and in_scope:
                types.setdefault(path, [])
                if m.group(1) not in types[path]:
                    types[path].append(m.group(1))
            if not stripped.startswith("#["):
                docs = []
        if not comment:
            depth += line.count("{") - line.count("}")
        while stack and depth <= stack[-1][1]:
            stack.pop()
        i += 1
    return fns, types


def signature(sig):
    """The wrapper's signature: the binding's, with wit-bindgen's runtime
    aliases spelled as the `alloc` types an app sees."""
    sig = sig.replace("_rt::Vec::<", "alloc::vec::Vec<").replace("_rt::Vec<", "alloc::vec::Vec<")
    sig = sig.replace("_rt::String", "alloc::string::String")
    sig = re.sub(r",\s*\)", ")", sig)
    sig = re.sub(r"\s*,\s*", ", ", sig)
    sig = re.sub(r"\s*->\s*", " -> ", sig)
    sig = re.sub(r"Result<\s*", "Result<", sig)
    return sig


def arguments(sig):
    """The argument names of a `pub fn name(a: T, b: U) -> R` signature."""
    start = sig.index("(")
    depth = 0
    end = start
    for k in range(start, len(sig)):
        if sig[k] in "([<":
            depth += 1
        elif sig[k] in ")]>":
            depth -= 1
            if depth == 0:
                end = k
                break
    inner = sig[start + 1 : end]
    names = []
    depth = 0
    current = ""
    for ch in inner:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            names.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        names.append(current)
    return [n.split(":")[0].strip() for n in names if n.strip()]


def render(fns, types):
    out = [HEADER, "//! The Phase 3 interfaces -- windows, widgets, events, drawing, sound,", "//! camera, speech -- as thin layers over the gui world's bindings", "//! (IC-298). Same signatures, same errors, same states; the SDK is the", "//! one place an app reaches them, whichever world it targets.", "", "#![allow(clippy::too_many_arguments)]", ""]
    by_package = {}
    for path in sorted(set(fns) | set(types)):
        _, package, interface = path.split("/")
        by_package.setdefault(package, []).append(interface)
    for package in PACKAGES:
        interfaces = sorted(set(by_package.get(package, [])))
        if not interfaces:
            continue
        out.append(f"/// `krate:{package}`: {', '.join(i for i in interfaces if i != 'types')}.")
        out.append(f"pub mod {package} {{")
        for interface in interfaces:
            path = f"krate/{package}/{interface}"
            names = types.get(path, [])
            functions = fns.get(path, [])
            if interface == "types":
                out.append("    /// The records and errors this package's interfaces share.")
                out.append("    pub mod types {")
                out.append(f"        pub use crate::bindings::krate::{package}::types::*;")
                out.append("    }")
                continue
            out.append(f"    /// `krate:{package}/{interface}`.")
            out.append(f"    pub mod {interface} {{")
            if names:
                out.append(f"        pub use crate::bindings::krate::{package}::{interface}::{{{', '.join(names)}}};")
            for name, sig, doc in functions:
                out.append("")
                for d in doc:
                    out.append(f"        /// {d}" if d else "        ///")
                out.append(f"        {signature(sig)} {{")
                out.append(f"            crate::bindings::krate::{package}::{interface}::{name}({', '.join(arguments(sig))})")
                out.append("        }")
            out.append("    }")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def formatted(text):
    """rustfmt's view of the rendering, so the committed file is formatted
    like the rest of the tree; the raw rendering when rustfmt is absent."""
    import shutil
    import subprocess
    import tempfile
    if not shutil.which("rustfmt"):
        return text
    with tempfile.NamedTemporaryFile("w", suffix=".rs", delete=False) as f:
        f.write(text)
        path = f.name
    try:
        subprocess.run(["rustfmt", "--edition", "2021", path], check=True, capture_output=True)
        return Path(path).read_text()
    except (OSError, subprocess.CalledProcessError):
        return text
    finally:
        Path(path).unlink(missing_ok=True)


def build(bindings=BINDINGS):
    fns, types = parse(bindings.read_text())
    return formatted(render(fns, types)), sum(len(v) for v in fns.values())


def self_test():
    failures = []

    def check(name, cond, detail=""):
        if not cond:
            failures.append(f"{name}: {detail}" if detail else name)

    sample = """
pub mod krate {
    pub mod ui {
        pub mod types {
            pub struct WindowSize { pub width: u32 }
            pub enum UiError { Unsupported }
        }
        pub mod window {
            use super::super::super::_rt;
            pub type UiError = super::super::super::krate::ui::types::UiError;
            pub type WindowSize = super::super::super::krate::ui::types::WindowSize;
            #[allow(unused_unsafe, clippy::all)]
            /// Create a host window and return its id.
            pub fn create(title: &str,size: WindowSize,) -> Result<u64,UiError>{
                unsafe { 0 }
            }
            /// Names it, like `{ title }` does.
            pub fn set_title(
                window: u64,
                title: &str,
            ) -> Result<(), UiError> {
                unsafe { 0 }
            }
        }
        pub mod clipboard {
            use super::super::super::_rt;
            pub type UiError = super::super::super::krate::ui::types::UiError;
            pub fn read_text() -> Result<_rt::String,UiError>{
                unsafe { 0 }
            }
        }
    }
    pub mod speech {
        pub mod transcription {
            pub enum SpeechError { Busy }
            impl SpeechError {
                pub fn name(&self) -> &'static str { "" }
            }
            pub fn transcribe(model_asset: &str,pcm: &[u8],) -> Result<_rt::Vec::<u8>,SpeechError>{
                unsafe { 0 }
            }
        }
    }
    pub mod io {
        pub mod stdio {
            pub fn stdout() -> u32 { 0 }
        }
    }
}
"""
    fns, types = parse(sample)
    check("functions are found under their interface", [f[0] for f in fns.get("krate/ui/window", [])] == ["create", "set_title"], str(fns))
    check("a method is not a function", [f[0] for f in fns.get("krate/speech/transcription", [])] == ["transcribe"], str(fns))
    check("phase 2 packages are left alone", "krate/io/stdio" not in fns)
    check("types are listed", types.get("krate/ui/window") == ["UiError", "WindowSize"], str(types))
    check("docs travel with the function", fns["krate/ui/window"][0][2] == ["Create a host window and return its id."], str(fns["krate/ui/window"][0][2]))
    out = render(fns, types)
    check("the wrapper keeps the signature", "pub fn create(title: &str, size: WindowSize) -> Result<u64, UiError> {" in out, out)
    check("the wrapper delegates with the same arguments", "crate::bindings::krate::ui::window::create(title, size)" in out, out)
    check("runtime aliases become alloc types", "-> Result<alloc::string::String, UiError>" in out and "Result<alloc::vec::Vec<u8>, SpeechError>" in out, out)
    check("types are re-exported beside the functions", "pub use crate::bindings::krate::ui::window::{UiError, WindowSize};" in out, out)
    check("the shared types module is re-exported whole", "pub use crate::bindings::krate::ui::types::*;" in out, out)
    check("the doc line is on the wrapper", "/// Create a host window and return its id.\n        pub fn create(" in out, out)
    check("rendering is stable", render(fns, types) == out)
    check("names of every argument are read past generics", arguments("pub fn f(a: Option<&str>, b: Result<u8, E>, c: &[f32]) -> u8") == ["a", "b", "c"])
    check("a formatted multi-line signature is read whole", "crate::bindings::krate::ui::window::set_title(window, title)" in out, out)
    check("a brace inside a doc comment does not lose the modules after it", "krate/speech/transcription" in fns, str(list(fns)))
    if failures:
        print("sdk-phase3-layer self-test FAILED:\n")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("sdk-phase3-layer self-test OK -- functions and types are read per interface, methods and Phase 2 packages are left out, wrappers keep the signature and delegate, aliases become alloc types, docs travel")
    return 0


def main(argv):
    if "--self-test" in argv:
        return self_test()
    text, count = build()
    if "--check" in argv:
        if not OUT.is_file() or OUT.read_text() != text:
            print(f"FAIL: {OUT.relative_to(ROOT)} is not what bindings_gui.rs generates; run scripts/sdk-phase3-layer.py and commit it", file=sys.stderr)
            return 1
        print(f"OK -- {OUT.relative_to(ROOT)} matches the gui bindings ({count} functions)")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}: {count} functions across {len(PACKAGES)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
